# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ciot/proto/v1/ciot.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ciot/proto/v1/ciot.proto',
  package='Ciot',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x63iot/proto/v1/ciot.proto\x12\x04\x43iot\"\t\n\x07\x43iotCfg\"\x1b\n\x08\x43iotInfo\x12\x0f\n\x07version\x18\x01 \x01(\x0c\",\n\nCiotStatus\x12\x1e\n\x05state\x18\x01 \x01(\x0e\x32\x0f.Ciot.CiotState\"0\n\x0b\x43iotReqData\x12\x10\n\x08iface_id\x18\x01 \x01(\r\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"K\n\x07\x43iotReq\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.Ciot.CiotReqType\x12\x1f\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x11.Ciot.CiotReqData\"\x89\x01\n\x08\x43iotData\x12\x1d\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\r.Ciot.CiotCfg\x12 \n\x06status\x18\x02 \x01(\x0b\x32\x10.Ciot.CiotStatus\x12\x1e\n\x07request\x18\x03 \x01(\x0b\x32\r.Ciot.CiotReq\x12\x1c\n\x04info\x18\x04 \x01(\x0b\x32\x0e.Ciot.CiotInfo*\x85\x01\n\tCiotState\x12\x13\n\x0f\x43IOT_STATE_IDLE\x10\x00\x12\x17\n\x13\x43IOT_STATE_STARTING\x10\x01\x12\x16\n\x12\x43IOT_STATE_STARTED\x10\x02\x12\x13\n\x0f\x43IOT_STATE_BUSY\x10\x03\x12\x1d\n\x10\x43IOT_STATE_ERROR\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*\x8a\x01\n\x0b\x43iotReqType\x12\x18\n\x14\x43IOT_REQ_TYPE_UNKOWN\x10\x00\x12 \n\x1c\x43IOT_REQ_TYPE_SAVE_IFACE_CFG\x10\x01\x12\"\n\x1e\x43IOT_REQ_TYPE_DELETE_IFACE_CFG\x10\x02\x12\x1b\n\x17\x43IOT_REQ_TYPE_PROXY_MSG\x10\x03*8\n\x15\x43iotSerializationType\x12\x1f\n\x1b\x43IOT_SERIALIZATION_PROTOBUF\x10\x00\x62\x06proto3'
)

_CIOTSTATE = _descriptor.EnumDescriptor(
  name='CiotState',
  full_name='Ciot.CiotState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CIOT_STATE_IDLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CIOT_STATE_STARTING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CIOT_STATE_STARTED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CIOT_STATE_BUSY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CIOT_STATE_ERROR', index=4, number=-1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=388,
  serialized_end=521,
)
_sym_db.RegisterEnumDescriptor(_CIOTSTATE)

CiotState = enum_type_wrapper.EnumTypeWrapper(_CIOTSTATE)
_CIOTREQTYPE = _descriptor.EnumDescriptor(
  name='CiotReqType',
  full_name='Ciot.CiotReqType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CIOT_REQ_TYPE_UNKOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CIOT_REQ_TYPE_SAVE_IFACE_CFG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CIOT_REQ_TYPE_DELETE_IFACE_CFG', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CIOT_REQ_TYPE_PROXY_MSG', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=524,
  serialized_end=662,
)
_sym_db.RegisterEnumDescriptor(_CIOTREQTYPE)

CiotReqType = enum_type_wrapper.EnumTypeWrapper(_CIOTREQTYPE)
_CIOTSERIALIZATIONTYPE = _descriptor.EnumDescriptor(
  name='CiotSerializationType',
  full_name='Ciot.CiotSerializationType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CIOT_SERIALIZATION_PROTOBUF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=664,
  serialized_end=720,
)
_sym_db.RegisterEnumDescriptor(_CIOTSERIALIZATIONTYPE)

CiotSerializationType = enum_type_wrapper.EnumTypeWrapper(_CIOTSERIALIZATIONTYPE)
CIOT_STATE_IDLE = 0
CIOT_STATE_STARTING = 1
CIOT_STATE_STARTED = 2
CIOT_STATE_BUSY = 3
CIOT_STATE_ERROR = -1
CIOT_REQ_TYPE_UNKOWN = 0
CIOT_REQ_TYPE_SAVE_IFACE_CFG = 1
CIOT_REQ_TYPE_DELETE_IFACE_CFG = 2
CIOT_REQ_TYPE_PROXY_MSG = 3
CIOT_SERIALIZATION_PROTOBUF = 0



_CIOTCFG = _descriptor.Descriptor(
  name='CiotCfg',
  full_name='Ciot.CiotCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=43,
)


_CIOTINFO = _descriptor.Descriptor(
  name='CiotInfo',
  full_name='Ciot.CiotInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Ciot.CiotInfo.version', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=72,
)


_CIOTSTATUS = _descriptor.Descriptor(
  name='CiotStatus',
  full_name='Ciot.CiotStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='Ciot.CiotStatus.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=118,
)


_CIOTREQDATA = _descriptor.Descriptor(
  name='CiotReqData',
  full_name='Ciot.CiotReqData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='iface_id', full_name='Ciot.CiotReqData.iface_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='Ciot.CiotReqData.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=168,
)


_CIOTREQ = _descriptor.Descriptor(
  name='CiotReq',
  full_name='Ciot.CiotReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Ciot.CiotReq.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Ciot.CiotReq.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=245,
)


_CIOTDATA = _descriptor.Descriptor(
  name='CiotData',
  full_name='Ciot.CiotData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='Ciot.CiotData.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='Ciot.CiotData.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='Ciot.CiotData.request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='Ciot.CiotData.info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=385,
)

_CIOTSTATUS.fields_by_name['state'].enum_type = _CIOTSTATE
_CIOTREQ.fields_by_name['type'].enum_type = _CIOTREQTYPE
_CIOTREQ.fields_by_name['data'].message_type = _CIOTREQDATA
_CIOTDATA.fields_by_name['config'].message_type = _CIOTCFG
_CIOTDATA.fields_by_name['status'].message_type = _CIOTSTATUS
_CIOTDATA.fields_by_name['request'].message_type = _CIOTREQ
_CIOTDATA.fields_by_name['info'].message_type = _CIOTINFO
DESCRIPTOR.message_types_by_name['CiotCfg'] = _CIOTCFG
DESCRIPTOR.message_types_by_name['CiotInfo'] = _CIOTINFO
DESCRIPTOR.message_types_by_name['CiotStatus'] = _CIOTSTATUS
DESCRIPTOR.message_types_by_name['CiotReqData'] = _CIOTREQDATA
DESCRIPTOR.message_types_by_name['CiotReq'] = _CIOTREQ
DESCRIPTOR.message_types_by_name['CiotData'] = _CIOTDATA
DESCRIPTOR.enum_types_by_name['CiotState'] = _CIOTSTATE
DESCRIPTOR.enum_types_by_name['CiotReqType'] = _CIOTREQTYPE
DESCRIPTOR.enum_types_by_name['CiotSerializationType'] = _CIOTSERIALIZATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CiotCfg = _reflection.GeneratedProtocolMessageType('CiotCfg', (_message.Message,), {
  'DESCRIPTOR' : _CIOTCFG,
  '__module__' : 'ciot.proto.v1.ciot_pb2'
  # @@protoc_insertion_point(class_scope:Ciot.CiotCfg)
  })
_sym_db.RegisterMessage(CiotCfg)

CiotInfo = _reflection.GeneratedProtocolMessageType('CiotInfo', (_message.Message,), {
  'DESCRIPTOR' : _CIOTINFO,
  '__module__' : 'ciot.proto.v1.ciot_pb2'
  # @@protoc_insertion_point(class_scope:Ciot.CiotInfo)
  })
_sym_db.RegisterMessage(CiotInfo)

CiotStatus = _reflection.GeneratedProtocolMessageType('CiotStatus', (_message.Message,), {
  'DESCRIPTOR' : _CIOTSTATUS,
  '__module__' : 'ciot.proto.v1.ciot_pb2'
  # @@protoc_insertion_point(class_scope:Ciot.CiotStatus)
  })
_sym_db.RegisterMessage(CiotStatus)

CiotReqData = _reflection.GeneratedProtocolMessageType('CiotReqData', (_message.Message,), {
  'DESCRIPTOR' : _CIOTREQDATA,
  '__module__' : 'ciot.proto.v1.ciot_pb2'
  # @@protoc_insertion_point(class_scope:Ciot.CiotReqData)
  })
_sym_db.RegisterMessage(CiotReqData)

CiotReq = _reflection.GeneratedProtocolMessageType('CiotReq', (_message.Message,), {
  'DESCRIPTOR' : _CIOTREQ,
  '__module__' : 'ciot.proto.v1.ciot_pb2'
  # @@protoc_insertion_point(class_scope:Ciot.CiotReq)
  })
_sym_db.RegisterMessage(CiotReq)

CiotData = _reflection.GeneratedProtocolMessageType('CiotData', (_message.Message,), {
  'DESCRIPTOR' : _CIOTDATA,
  '__module__' : 'ciot.proto.v1.ciot_pb2'
  # @@protoc_insertion_point(class_scope:Ciot.CiotData)
  })
_sym_db.RegisterMessage(CiotData)


# @@protoc_insertion_point(module_scope)
