# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ciot/proto/v1/http_server.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63iot/proto/v1/http_server.proto\x12\x04\x43iot\"=\n\rHttpServerCfg\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05route\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"G\n\x10HttpServerStatus\x12$\n\x05state\x18\x01 \x01(\x0e\x32\x15.Ciot.HttpServerState\x12\r\n\x05\x65rror\x18\x02 \x01(\x05\"6\n\rHttpServerReq\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.Ciot.HttpServerReqType\"\x83\x01\n\x0eHttpServerData\x12#\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x13.Ciot.HttpServerCfg\x12&\n\x06status\x18\x02 \x01(\x0b\x32\x16.Ciot.HttpServerStatus\x12$\n\x07request\x18\x03 \x01(\x0b\x32\x13.Ciot.HttpServerReq*u\n\x0fHttpServerState\x12\x1d\n\x19HTTP_SERVER_STATE_STOPPED\x10\x00\x12\x1d\n\x19HTTP_SERVER_STATE_STARTED\x10\x01\x12$\n\x17HTTP_SERVER_STATE_ERROR\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*4\n\x11HttpServerReqType\x12\x1f\n\x1bHTTP_SERVER_REQ_TYPE_UNKOWN\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ciot.proto.v1.http_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HTTPSERVERSTATE']._serialized_start=367
  _globals['_HTTPSERVERSTATE']._serialized_end=484
  _globals['_HTTPSERVERREQTYPE']._serialized_start=486
  _globals['_HTTPSERVERREQTYPE']._serialized_end=538
  _globals['_HTTPSERVERCFG']._serialized_start=41
  _globals['_HTTPSERVERCFG']._serialized_end=102
  _globals['_HTTPSERVERSTATUS']._serialized_start=104
  _globals['_HTTPSERVERSTATUS']._serialized_end=175
  _globals['_HTTPSERVERREQ']._serialized_start=177
  _globals['_HTTPSERVERREQ']._serialized_end=231
  _globals['_HTTPSERVERDATA']._serialized_start=234
  _globals['_HTTPSERVERDATA']._serialized_end=365
# @@protoc_insertion_point(module_scope)
