# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ciot/proto/v1/socket.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ciot/proto/v1/socket.proto',
  package='Ciot',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x63iot/proto/v1/socket.proto\x12\x04\x43iot\"J\n\tSocketCfg\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.Ciot.SocketType\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"?\n\x0cSocketStatus\x12 \n\x05state\x18\x01 \x01(\x0e\x32\x11.Ciot.SocketState\x12\r\n\x05\x65rror\x18\x02 \x01(\x05\"\x0c\n\nSocketInfo\".\n\tSocketReq\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.Ciot.SocketReqType\"\x93\x01\n\nSocketData\x12\x1f\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x0f.Ciot.SocketCfg\x12\"\n\x06status\x18\x02 \x01(\x0b\x32\x12.Ciot.SocketStatus\x12 \n\x07request\x18\x03 \x01(\x0b\x32\x0f.Ciot.SocketReq\x12\x1e\n\x04info\x18\x04 \x01(\x0b\x32\x10.Ciot.SocketInfo*^\n\x0bSocketState\x12\x17\n\x13SOCKET_STATE_CLOSED\x10\x00\x12\x15\n\x11SOCKET_STATE_OPEN\x10\x01\x12\x1f\n\x12SOCKET_STATE_ERROR\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*+\n\rSocketReqType\x12\x1a\n\x16SOCKET_REQ_TYPE_UNKOWN\x10\x00*Z\n\nSocketType\x12\x14\n\x10SOCKET_TYPE_NONE\x10\x00\x12\x1a\n\x16SOCKET_TYPE_TCP_SERVER\x10\x01\x12\x1a\n\x16SOCKET_TYPE_TCP_CLIENT\x10\x02\x62\x06proto3'
)

_SOCKETSTATE = _descriptor.EnumDescriptor(
  name='SocketState',
  full_name='Ciot.SocketState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOCKET_STATE_CLOSED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOCKET_STATE_OPEN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOCKET_STATE_ERROR', index=2, number=-1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=389,
  serialized_end=483,
)
_sym_db.RegisterEnumDescriptor(_SOCKETSTATE)

SocketState = enum_type_wrapper.EnumTypeWrapper(_SOCKETSTATE)
_SOCKETREQTYPE = _descriptor.EnumDescriptor(
  name='SocketReqType',
  full_name='Ciot.SocketReqType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOCKET_REQ_TYPE_UNKOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=485,
  serialized_end=528,
)
_sym_db.RegisterEnumDescriptor(_SOCKETREQTYPE)

SocketReqType = enum_type_wrapper.EnumTypeWrapper(_SOCKETREQTYPE)
_SOCKETTYPE = _descriptor.EnumDescriptor(
  name='SocketType',
  full_name='Ciot.SocketType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOCKET_TYPE_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOCKET_TYPE_TCP_SERVER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOCKET_TYPE_TCP_CLIENT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=530,
  serialized_end=620,
)
_sym_db.RegisterEnumDescriptor(_SOCKETTYPE)

SocketType = enum_type_wrapper.EnumTypeWrapper(_SOCKETTYPE)
SOCKET_STATE_CLOSED = 0
SOCKET_STATE_OPEN = 1
SOCKET_STATE_ERROR = -1
SOCKET_REQ_TYPE_UNKOWN = 0
SOCKET_TYPE_NONE = 0
SOCKET_TYPE_TCP_SERVER = 1
SOCKET_TYPE_TCP_CLIENT = 2



_SOCKETCFG = _descriptor.Descriptor(
  name='SocketCfg',
  full_name='Ciot.SocketCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Ciot.SocketCfg.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='Ciot.SocketCfg.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='Ciot.SocketCfg.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=110,
)


_SOCKETSTATUS = _descriptor.Descriptor(
  name='SocketStatus',
  full_name='Ciot.SocketStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='Ciot.SocketStatus.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='Ciot.SocketStatus.error', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=175,
)


_SOCKETINFO = _descriptor.Descriptor(
  name='SocketInfo',
  full_name='Ciot.SocketInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=189,
)


_SOCKETREQ = _descriptor.Descriptor(
  name='SocketReq',
  full_name='Ciot.SocketReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Ciot.SocketReq.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=237,
)


_SOCKETDATA = _descriptor.Descriptor(
  name='SocketData',
  full_name='Ciot.SocketData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='Ciot.SocketData.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='Ciot.SocketData.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='Ciot.SocketData.request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='Ciot.SocketData.info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=387,
)

_SOCKETCFG.fields_by_name['type'].enum_type = _SOCKETTYPE
_SOCKETSTATUS.fields_by_name['state'].enum_type = _SOCKETSTATE
_SOCKETREQ.fields_by_name['type'].enum_type = _SOCKETREQTYPE
_SOCKETDATA.fields_by_name['config'].message_type = _SOCKETCFG
_SOCKETDATA.fields_by_name['status'].message_type = _SOCKETSTATUS
_SOCKETDATA.fields_by_name['request'].message_type = _SOCKETREQ
_SOCKETDATA.fields_by_name['info'].message_type = _SOCKETINFO
DESCRIPTOR.message_types_by_name['SocketCfg'] = _SOCKETCFG
DESCRIPTOR.message_types_by_name['SocketStatus'] = _SOCKETSTATUS
DESCRIPTOR.message_types_by_name['SocketInfo'] = _SOCKETINFO
DESCRIPTOR.message_types_by_name['SocketReq'] = _SOCKETREQ
DESCRIPTOR.message_types_by_name['SocketData'] = _SOCKETDATA
DESCRIPTOR.enum_types_by_name['SocketState'] = _SOCKETSTATE
DESCRIPTOR.enum_types_by_name['SocketReqType'] = _SOCKETREQTYPE
DESCRIPTOR.enum_types_by_name['SocketType'] = _SOCKETTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SocketCfg = _reflection.GeneratedProtocolMessageType('SocketCfg', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETCFG,
  '__module__' : 'ciot.proto.v1.socket_pb2'
  # @@protoc_insertion_point(class_scope:Ciot.SocketCfg)
  })
_sym_db.RegisterMessage(SocketCfg)

SocketStatus = _reflection.GeneratedProtocolMessageType('SocketStatus', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETSTATUS,
  '__module__' : 'ciot.proto.v1.socket_pb2'
  # @@protoc_insertion_point(class_scope:Ciot.SocketStatus)
  })
_sym_db.RegisterMessage(SocketStatus)

SocketInfo = _reflection.GeneratedProtocolMessageType('SocketInfo', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETINFO,
  '__module__' : 'ciot.proto.v1.socket_pb2'
  # @@protoc_insertion_point(class_scope:Ciot.SocketInfo)
  })
_sym_db.RegisterMessage(SocketInfo)

SocketReq = _reflection.GeneratedProtocolMessageType('SocketReq', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETREQ,
  '__module__' : 'ciot.proto.v1.socket_pb2'
  # @@protoc_insertion_point(class_scope:Ciot.SocketReq)
  })
_sym_db.RegisterMessage(SocketReq)

SocketData = _reflection.GeneratedProtocolMessageType('SocketData', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETDATA,
  '__module__' : 'ciot.proto.v1.socket_pb2'
  # @@protoc_insertion_point(class_scope:Ciot.SocketData)
  })
_sym_db.RegisterMessage(SocketData)


# @@protoc_insertion_point(module_scope)
