/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ciot/proto/v1/ciot.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ciot/proto/v1/ciot.pb-c.h"
void   ciot__ciot_cfg__init
                     (Ciot__CiotCfg         *message)
{
  static const Ciot__CiotCfg init_value = CIOT__CIOT_CFG__INIT;
  *message = init_value;
}
size_t ciot__ciot_cfg__get_packed_size
                     (const Ciot__CiotCfg *message)
{
  assert(message->base.descriptor == &ciot__ciot_cfg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__ciot_cfg__pack
                     (const Ciot__CiotCfg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__ciot_cfg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__ciot_cfg__pack_to_buffer
                     (const Ciot__CiotCfg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__ciot_cfg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__CiotCfg *
       ciot__ciot_cfg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__CiotCfg *)
     protobuf_c_message_unpack (&ciot__ciot_cfg__descriptor,
                                allocator, len, data);
}
void   ciot__ciot_cfg__free_unpacked
                     (Ciot__CiotCfg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__ciot_cfg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__ciot_info__init
                     (Ciot__CiotInfo         *message)
{
  static const Ciot__CiotInfo init_value = CIOT__CIOT_INFO__INIT;
  *message = init_value;
}
size_t ciot__ciot_info__get_packed_size
                     (const Ciot__CiotInfo *message)
{
  assert(message->base.descriptor == &ciot__ciot_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__ciot_info__pack
                     (const Ciot__CiotInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__ciot_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__ciot_info__pack_to_buffer
                     (const Ciot__CiotInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__ciot_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__CiotInfo *
       ciot__ciot_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__CiotInfo *)
     protobuf_c_message_unpack (&ciot__ciot_info__descriptor,
                                allocator, len, data);
}
void   ciot__ciot_info__free_unpacked
                     (Ciot__CiotInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__ciot_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__ciot_status__init
                     (Ciot__CiotStatus         *message)
{
  static const Ciot__CiotStatus init_value = CIOT__CIOT_STATUS__INIT;
  *message = init_value;
}
size_t ciot__ciot_status__get_packed_size
                     (const Ciot__CiotStatus *message)
{
  assert(message->base.descriptor == &ciot__ciot_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__ciot_status__pack
                     (const Ciot__CiotStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__ciot_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__ciot_status__pack_to_buffer
                     (const Ciot__CiotStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__ciot_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__CiotStatus *
       ciot__ciot_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__CiotStatus *)
     protobuf_c_message_unpack (&ciot__ciot_status__descriptor,
                                allocator, len, data);
}
void   ciot__ciot_status__free_unpacked
                     (Ciot__CiotStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__ciot_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__ciot_req_data__init
                     (Ciot__CiotReqData         *message)
{
  static const Ciot__CiotReqData init_value = CIOT__CIOT_REQ_DATA__INIT;
  *message = init_value;
}
size_t ciot__ciot_req_data__get_packed_size
                     (const Ciot__CiotReqData *message)
{
  assert(message->base.descriptor == &ciot__ciot_req_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__ciot_req_data__pack
                     (const Ciot__CiotReqData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__ciot_req_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__ciot_req_data__pack_to_buffer
                     (const Ciot__CiotReqData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__ciot_req_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__CiotReqData *
       ciot__ciot_req_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__CiotReqData *)
     protobuf_c_message_unpack (&ciot__ciot_req_data__descriptor,
                                allocator, len, data);
}
void   ciot__ciot_req_data__free_unpacked
                     (Ciot__CiotReqData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__ciot_req_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__ciot_req__init
                     (Ciot__CiotReq         *message)
{
  static const Ciot__CiotReq init_value = CIOT__CIOT_REQ__INIT;
  *message = init_value;
}
size_t ciot__ciot_req__get_packed_size
                     (const Ciot__CiotReq *message)
{
  assert(message->base.descriptor == &ciot__ciot_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__ciot_req__pack
                     (const Ciot__CiotReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__ciot_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__ciot_req__pack_to_buffer
                     (const Ciot__CiotReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__ciot_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__CiotReq *
       ciot__ciot_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__CiotReq *)
     protobuf_c_message_unpack (&ciot__ciot_req__descriptor,
                                allocator, len, data);
}
void   ciot__ciot_req__free_unpacked
                     (Ciot__CiotReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__ciot_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__ciot_data__init
                     (Ciot__CiotData         *message)
{
  static const Ciot__CiotData init_value = CIOT__CIOT_DATA__INIT;
  *message = init_value;
}
size_t ciot__ciot_data__get_packed_size
                     (const Ciot__CiotData *message)
{
  assert(message->base.descriptor == &ciot__ciot_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__ciot_data__pack
                     (const Ciot__CiotData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__ciot_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__ciot_data__pack_to_buffer
                     (const Ciot__CiotData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__ciot_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__CiotData *
       ciot__ciot_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__CiotData *)
     protobuf_c_message_unpack (&ciot__ciot_data__descriptor,
                                allocator, len, data);
}
void   ciot__ciot_data__free_unpacked
                     (Ciot__CiotData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__ciot_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define ciot__ciot_cfg__field_descriptors NULL
#define ciot__ciot_cfg__field_indices_by_name NULL
#define ciot__ciot_cfg__number_ranges NULL
const ProtobufCMessageDescriptor ciot__ciot_cfg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.CiotCfg",
  "CiotCfg",
  "Ciot__CiotCfg",
  "Ciot",
  sizeof(Ciot__CiotCfg),
  0,
  ciot__ciot_cfg__field_descriptors,
  ciot__ciot_cfg__field_indices_by_name,
  0,  ciot__ciot_cfg__number_ranges,
  (ProtobufCMessageInit) ciot__ciot_cfg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__ciot_info__field_descriptors[1] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Ciot__CiotInfo, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__ciot_info__field_indices_by_name[] = {
  0,   /* field[0] = version */
};
static const ProtobufCIntRange ciot__ciot_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ciot__ciot_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.CiotInfo",
  "CiotInfo",
  "Ciot__CiotInfo",
  "Ciot",
  sizeof(Ciot__CiotInfo),
  1,
  ciot__ciot_info__field_descriptors,
  ciot__ciot_info__field_indices_by_name,
  1,  ciot__ciot_info__number_ranges,
  (ProtobufCMessageInit) ciot__ciot_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__ciot_status__field_descriptors[2] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__CiotStatus, state),
    &ciot__ciot_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__CiotStatus, info),
    &ciot__ciot_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__ciot_status__field_indices_by_name[] = {
  1,   /* field[1] = info */
  0,   /* field[0] = state */
};
static const ProtobufCIntRange ciot__ciot_status__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ciot__ciot_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.CiotStatus",
  "CiotStatus",
  "Ciot__CiotStatus",
  "Ciot",
  sizeof(Ciot__CiotStatus),
  2,
  ciot__ciot_status__field_descriptors,
  ciot__ciot_status__field_indices_by_name,
  2,  ciot__ciot_status__number_ranges,
  (ProtobufCMessageInit) ciot__ciot_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__ciot_req_data__field_descriptors[2] =
{
  {
    "iface_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__CiotReqData, iface_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Ciot__CiotReqData, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__ciot_req_data__field_indices_by_name[] = {
  0,   /* field[0] = iface_id */
  1,   /* field[1] = payload */
};
static const ProtobufCIntRange ciot__ciot_req_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ciot__ciot_req_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.CiotReqData",
  "CiotReqData",
  "Ciot__CiotReqData",
  "Ciot",
  sizeof(Ciot__CiotReqData),
  2,
  ciot__ciot_req_data__field_descriptors,
  ciot__ciot_req_data__field_indices_by_name,
  1,  ciot__ciot_req_data__number_ranges,
  (ProtobufCMessageInit) ciot__ciot_req_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__ciot_req__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__CiotReq, type),
    &ciot__ciot_req_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__CiotReq, data),
    &ciot__ciot_req_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__ciot_req__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ciot__ciot_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ciot__ciot_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.CiotReq",
  "CiotReq",
  "Ciot__CiotReq",
  "Ciot",
  sizeof(Ciot__CiotReq),
  2,
  ciot__ciot_req__field_descriptors,
  ciot__ciot_req__field_indices_by_name,
  1,  ciot__ciot_req__number_ranges,
  (ProtobufCMessageInit) ciot__ciot_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__ciot_data__field_descriptors[3] =
{
  {
    "config",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__CiotData, config),
    &ciot__ciot_cfg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__CiotData, status),
    &ciot__ciot_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__CiotData, request),
    &ciot__ciot_req__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__ciot_data__field_indices_by_name[] = {
  0,   /* field[0] = config */
  2,   /* field[2] = request */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ciot__ciot_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ciot__ciot_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.CiotData",
  "CiotData",
  "Ciot__CiotData",
  "Ciot",
  sizeof(Ciot__CiotData),
  3,
  ciot__ciot_data__field_descriptors,
  ciot__ciot_data__field_indices_by_name,
  1,  ciot__ciot_data__number_ranges,
  (ProtobufCMessageInit) ciot__ciot_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ciot__ciot_state__enum_values_by_number[3] =
{
  { "CIOT_STATE_ERROR", "CIOT__CIOT_STATE__CIOT_STATE_ERROR", -1 },
  { "CIOT_STATE_IDLE", "CIOT__CIOT_STATE__CIOT_STATE_IDLE", 0 },
  { "CIOT_STATE_BUSY", "CIOT__CIOT_STATE__CIOT_STATE_BUSY", 1 },
};
static const ProtobufCIntRange ciot__ciot_state__value_ranges[] = {
{-1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ciot__ciot_state__enum_values_by_name[3] =
{
  { "CIOT_STATE_BUSY", 2 },
  { "CIOT_STATE_ERROR", 0 },
  { "CIOT_STATE_IDLE", 1 },
};
const ProtobufCEnumDescriptor ciot__ciot_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.CiotState",
  "CiotState",
  "Ciot__CiotState",
  "Ciot",
  3,
  ciot__ciot_state__enum_values_by_number,
  3,
  ciot__ciot_state__enum_values_by_name,
  1,
  ciot__ciot_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ciot__ciot_req_type__enum_values_by_number[4] =
{
  { "CIOT_REQ_TYPE_UNKOWN", "CIOT__CIOT_REQ_TYPE__CIOT_REQ_TYPE_UNKOWN", 0 },
  { "CIOT_REQ_TYPE_SAVE_IFACE_CFG", "CIOT__CIOT_REQ_TYPE__CIOT_REQ_TYPE_SAVE_IFACE_CFG", 1 },
  { "CIOT_REQ_TYPE_DELETE_IFACE_CFG", "CIOT__CIOT_REQ_TYPE__CIOT_REQ_TYPE_DELETE_IFACE_CFG", 2 },
  { "CIOT_REQ_TYPE_PROXY_MSG", "CIOT__CIOT_REQ_TYPE__CIOT_REQ_TYPE_PROXY_MSG", 3 },
};
static const ProtobufCIntRange ciot__ciot_req_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex ciot__ciot_req_type__enum_values_by_name[4] =
{
  { "CIOT_REQ_TYPE_DELETE_IFACE_CFG", 2 },
  { "CIOT_REQ_TYPE_PROXY_MSG", 3 },
  { "CIOT_REQ_TYPE_SAVE_IFACE_CFG", 1 },
  { "CIOT_REQ_TYPE_UNKOWN", 0 },
};
const ProtobufCEnumDescriptor ciot__ciot_req_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.CiotReqType",
  "CiotReqType",
  "Ciot__CiotReqType",
  "Ciot",
  4,
  ciot__ciot_req_type__enum_values_by_number,
  4,
  ciot__ciot_req_type__enum_values_by_name,
  1,
  ciot__ciot_req_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ciot__ciot_serialization_type__enum_values_by_number[2] =
{
  { "CIOT_SERIALIZATION_NONE", "CIOT__CIOT_SERIALIZATION_TYPE__CIOT_SERIALIZATION_NONE", 0 },
  { "CIOT_SERIALIZATION_PROTOBUF", "CIOT__CIOT_SERIALIZATION_TYPE__CIOT_SERIALIZATION_PROTOBUF", 1 },
};
static const ProtobufCIntRange ciot__ciot_serialization_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex ciot__ciot_serialization_type__enum_values_by_name[2] =
{
  { "CIOT_SERIALIZATION_NONE", 0 },
  { "CIOT_SERIALIZATION_PROTOBUF", 1 },
};
const ProtobufCEnumDescriptor ciot__ciot_serialization_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.CiotSerializationType",
  "CiotSerializationType",
  "Ciot__CiotSerializationType",
  "Ciot",
  2,
  ciot__ciot_serialization_type__enum_values_by_number,
  2,
  ciot__ciot_serialization_type__enum_values_by_name,
  1,
  ciot__ciot_serialization_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
