/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ciot/proto/v1/dfu.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ciot/proto/v1/dfu.pb-c.h"
void   ciot__dfu_cfg__init
                     (Ciot__DfuCfg         *message)
{
  static const Ciot__DfuCfg init_value = CIOT__DFU_CFG__INIT;
  *message = init_value;
}
size_t ciot__dfu_cfg__get_packed_size
                     (const Ciot__DfuCfg *message)
{
  assert(message->base.descriptor == &ciot__dfu_cfg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__dfu_cfg__pack
                     (const Ciot__DfuCfg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__dfu_cfg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__dfu_cfg__pack_to_buffer
                     (const Ciot__DfuCfg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__dfu_cfg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__DfuCfg *
       ciot__dfu_cfg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__DfuCfg *)
     protobuf_c_message_unpack (&ciot__dfu_cfg__descriptor,
                                allocator, len, data);
}
void   ciot__dfu_cfg__free_unpacked
                     (Ciot__DfuCfg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__dfu_cfg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__dfu_status__init
                     (Ciot__DfuStatus         *message)
{
  static const Ciot__DfuStatus init_value = CIOT__DFU_STATUS__INIT;
  *message = init_value;
}
size_t ciot__dfu_status__get_packed_size
                     (const Ciot__DfuStatus *message)
{
  assert(message->base.descriptor == &ciot__dfu_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__dfu_status__pack
                     (const Ciot__DfuStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__dfu_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__dfu_status__pack_to_buffer
                     (const Ciot__DfuStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__dfu_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__DfuStatus *
       ciot__dfu_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__DfuStatus *)
     protobuf_c_message_unpack (&ciot__dfu_status__descriptor,
                                allocator, len, data);
}
void   ciot__dfu_status__free_unpacked
                     (Ciot__DfuStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__dfu_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__dfu_req__init
                     (Ciot__DfuReq         *message)
{
  static const Ciot__DfuReq init_value = CIOT__DFU_REQ__INIT;
  *message = init_value;
}
size_t ciot__dfu_req__get_packed_size
                     (const Ciot__DfuReq *message)
{
  assert(message->base.descriptor == &ciot__dfu_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__dfu_req__pack
                     (const Ciot__DfuReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__dfu_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__dfu_req__pack_to_buffer
                     (const Ciot__DfuReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__dfu_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__DfuReq *
       ciot__dfu_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__DfuReq *)
     protobuf_c_message_unpack (&ciot__dfu_req__descriptor,
                                allocator, len, data);
}
void   ciot__dfu_req__free_unpacked
                     (Ciot__DfuReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__dfu_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__dfu_data__init
                     (Ciot__DfuData         *message)
{
  static const Ciot__DfuData init_value = CIOT__DFU_DATA__INIT;
  *message = init_value;
}
size_t ciot__dfu_data__get_packed_size
                     (const Ciot__DfuData *message)
{
  assert(message->base.descriptor == &ciot__dfu_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__dfu_data__pack
                     (const Ciot__DfuData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__dfu_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__dfu_data__pack_to_buffer
                     (const Ciot__DfuData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__dfu_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__DfuData *
       ciot__dfu_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__DfuData *)
     protobuf_c_message_unpack (&ciot__dfu_data__descriptor,
                                allocator, len, data);
}
void   ciot__dfu_data__free_unpacked
                     (Ciot__DfuData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__dfu_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ciot__dfu_cfg__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__DfuCfg, type),
    &ciot__dfu_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__dfu_cfg__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ciot__dfu_cfg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ciot__dfu_cfg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.DfuCfg",
  "DfuCfg",
  "Ciot__DfuCfg",
  "Ciot",
  sizeof(Ciot__DfuCfg),
  1,
  ciot__dfu_cfg__field_descriptors,
  ciot__dfu_cfg__field_indices_by_name,
  1,  ciot__dfu_cfg__number_ranges,
  (ProtobufCMessageInit) ciot__dfu_cfg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__dfu_status__field_descriptors[5] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__DfuStatus, state),
    &ciot__dfu_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__DfuStatus, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__DfuStatus, error),
    &ciot_err__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_size",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__DfuStatus, image_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image_written",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__DfuStatus, image_written),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__dfu_status__field_indices_by_name[] = {
  1,   /* field[1] = code */
  2,   /* field[2] = error */
  3,   /* field[3] = image_size */
  4,   /* field[4] = image_written */
  0,   /* field[0] = state */
};
static const ProtobufCIntRange ciot__dfu_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ciot__dfu_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.DfuStatus",
  "DfuStatus",
  "Ciot__DfuStatus",
  "Ciot",
  sizeof(Ciot__DfuStatus),
  5,
  ciot__dfu_status__field_descriptors,
  ciot__dfu_status__field_indices_by_name,
  1,  ciot__dfu_status__number_ranges,
  (ProtobufCMessageInit) ciot__dfu_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__dfu_req__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__DfuReq, type),
    &ciot__dfu_req_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__dfu_req__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ciot__dfu_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ciot__dfu_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.DfuReq",
  "DfuReq",
  "Ciot__DfuReq",
  "Ciot",
  sizeof(Ciot__DfuReq),
  1,
  ciot__dfu_req__field_descriptors,
  ciot__dfu_req__field_indices_by_name,
  1,  ciot__dfu_req__number_ranges,
  (ProtobufCMessageInit) ciot__dfu_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__dfu_data__field_descriptors[3] =
{
  {
    "config",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__DfuData, config),
    &ciot__dfu_cfg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__DfuData, status),
    &ciot__dfu_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__DfuData, request),
    &ciot__dfu_req__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__dfu_data__field_indices_by_name[] = {
  0,   /* field[0] = config */
  2,   /* field[2] = request */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ciot__dfu_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ciot__dfu_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.DfuData",
  "DfuData",
  "Ciot__DfuData",
  "Ciot",
  sizeof(Ciot__DfuData),
  3,
  ciot__dfu_data__field_descriptors,
  ciot__dfu_data__field_indices_by_name,
  1,  ciot__dfu_data__number_ranges,
  (ProtobufCMessageInit) ciot__dfu_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ciot__dfu_state__enum_values_by_number[6] =
{
  { "DFU_STATE_IDLE", "CIOT__DFU_STATE__DFU_STATE_IDLE", 0 },
  { "DFU_STATE_STARTING", "CIOT__DFU_STATE__DFU_STATE_STARTING", 1 },
  { "DFU_STATE_STARTED", "CIOT__DFU_STATE__DFU_STATE_STARTED", 2 },
  { "DFU_STATE_IN_PROGRESS", "CIOT__DFU_STATE__DFU_STATE_IN_PROGRESS", 3 },
  { "DFU_STATE_COMPLETED", "CIOT__DFU_STATE__DFU_STATE_COMPLETED", 4 },
  { "DFU_STATE_ERROR", "CIOT__DFU_STATE__DFU_STATE_ERROR", 5 },
};
static const ProtobufCIntRange ciot__dfu_state__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex ciot__dfu_state__enum_values_by_name[6] =
{
  { "DFU_STATE_COMPLETED", 4 },
  { "DFU_STATE_ERROR", 5 },
  { "DFU_STATE_IDLE", 0 },
  { "DFU_STATE_IN_PROGRESS", 3 },
  { "DFU_STATE_STARTED", 2 },
  { "DFU_STATE_STARTING", 1 },
};
const ProtobufCEnumDescriptor ciot__dfu_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.DfuState",
  "DfuState",
  "Ciot__DfuState",
  "Ciot",
  6,
  ciot__dfu_state__enum_values_by_number,
  6,
  ciot__dfu_state__enum_values_by_name,
  1,
  ciot__dfu_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ciot__dfu_req_type__enum_values_by_number[1] =
{
  { "DFU_REQ_TYPE_UNKOWN", "CIOT__DFU_REQ_TYPE__DFU_REQ_TYPE_UNKOWN", 0 },
};
static const ProtobufCIntRange ciot__dfu_req_type__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex ciot__dfu_req_type__enum_values_by_name[1] =
{
  { "DFU_REQ_TYPE_UNKOWN", 0 },
};
const ProtobufCEnumDescriptor ciot__dfu_req_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.DfuReqType",
  "DfuReqType",
  "Ciot__DfuReqType",
  "Ciot",
  1,
  ciot__dfu_req_type__enum_values_by_number,
  1,
  ciot__dfu_req_type__enum_values_by_name,
  1,
  ciot__dfu_req_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ciot__dfu_type__enum_values_by_number[4] =
{
  { "DFU_TYPE_UNKNOWN", "CIOT__DFU_TYPE__DFU_TYPE_UNKNOWN", 0 },
  { "DFU_TYPE_UART", "CIOT__DFU_TYPE__DFU_TYPE_UART", 1 },
  { "DFU_TYPE_USB", "CIOT__DFU_TYPE__DFU_TYPE_USB", 2 },
  { "DFU_TYPE_BLE", "CIOT__DFU_TYPE__DFU_TYPE_BLE", 3 },
};
static const ProtobufCIntRange ciot__dfu_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex ciot__dfu_type__enum_values_by_name[4] =
{
  { "DFU_TYPE_BLE", 3 },
  { "DFU_TYPE_UART", 1 },
  { "DFU_TYPE_UNKNOWN", 0 },
  { "DFU_TYPE_USB", 2 },
};
const ProtobufCEnumDescriptor ciot__dfu_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.DfuType",
  "DfuType",
  "Ciot__DfuType",
  "Ciot",
  4,
  ciot__dfu_type__enum_values_by_number,
  4,
  ciot__dfu_type__enum_values_by_name,
  1,
  ciot__dfu_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
