/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ciot/proto/v1/errors.proto */

#ifndef PROTOBUF_C_ciot_2fproto_2fv1_2ferrors_2eproto__INCLUDED
#define PROTOBUF_C_ciot_2fproto_2fv1_2ferrors_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

/*
 * Error codes
 */
typedef enum _CiotErr {
  /*
   * No error
   */
  CIOT_ERR__OK = 0,
  /*
   * Null argunment
   */
  CIOT_ERR__NULL_ARG = 1,
  /*
   * Invalid ID
   */
  CIOT_ERR__INVALID_ID = 2,
  /*
   * Invalid Type
   */
  CIOT_ERR__INVALID_TYPE = 3,
  /*
   * Memory overflow
   */
  CIOT_ERR__OVERFLOW = 4,
  /*
   * Not implemented
   */
  CIOT_ERR__NOT_IMPLEMENTED = 5,
  /*
   * Not supported
   */
  CIOT_ERR__NOT_SUPPORTED = 6,
  /*
   * Busy
   */
  CIOT_ERR__BUSY = 7,
  /*
   * Invalid state
   */
  CIOT_ERR__INVALID_STATE = 8,
  /*
   * Serialization error
   */
  CIOT_ERR__SERIALIZATION = 9,
  /*
   * Deserialization error
   */
  CIOT_ERR__DESERIALIZATION = 10,
  /*
   * Error sending data
   */
  CIOT_ERR__SEND_DATA = 11,
  /*
   * Error on data receive
   */
  CIOT_ERR__RECV_DATA = 12,
  /*
   * Invalid size
   */
  CIOT_ERR__INVALID_SIZE = 13,
  /*
   * Closed
   */
  CIOT_ERR__CLOSED = 14,
  /*
   * Resource not found
   */
  CIOT_ERR__NOT_FOUND = 15,
  /*
   * Validation failed
   */
  CIOT_ERR__VALIDATION_FAILED = 16,
  /*
   * Connection failed
   */
  CIOT_ERR__CONNECTION = 17,
  /*
   * Disconnection failed
   */
  CIOT_ERR__DISCONNECTION = 18,
  /*
   * Unknown exception occours
   */
  CIOT_ERR__EXCEPTION = 19,
  /*
   * Invalid argument detected
   */
  CIOT_ERR__INVALID_ARG = 20,
  /*
   * Insuficient memory
   */
  CIOT_ERR__NO_MEMORY = 21,
  /*
   * Timeout
   */
  CIOT_ERR__TIMEOUT = 22,
  /*
   * Internal error on mongoose framework
   */
  CIOT_ERR__MONGOOSE = 23,
  /*
   * Requested operation is impossible
   */
  CIOT_ERR__IMPOSSIBLE_OP = 24,
  /*
   * Checksum validation error
   */
  CIOT_ERR__CHECKSUM = 25,
  /*
   * Protocol validation error
   */
  CIOT_ERR__PROTOCOL_VIOLATION = 26,
  /*
   * Operation failed
   */
  CIOT_ERR__FAIL = -1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CIOT_ERR)
} CiotErr;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    ciot_err__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ciot_2fproto_2fv1_2ferrors_2eproto__INCLUDED */
