/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ciot/proto/v1/errors.proto */

#ifndef PROTOBUF_C_ciot_2fproto_2fv1_2ferrors_2eproto__INCLUDED
#define PROTOBUF_C_ciot_2fproto_2fv1_2ferrors_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

/*
 * Error codes
 */
typedef enum _Ciot__CiotErr {
  /*
   * No error
   */
  CIOT__CIOT_ERR__CIOT_OK = 0,
  /*
   * Null argunment
   */
  CIOT__CIOT_ERR__CIOT_ERR_NULL_ARG = 1,
  /*
   * Invalid ID
   */
  CIOT__CIOT_ERR__CIOT_ERR_INVALID_ID = 2,
  /*
   * Invalid Type
   */
  CIOT__CIOT_ERR__CIOT_ERR_INVALID_TYPE = 3,
  /*
   * Memory overflow
   */
  CIOT__CIOT_ERR__CIOT_ERR_OVERFLOW = 4,
  /*
   * Not implemented
   */
  CIOT__CIOT_ERR__CIOT_ERR_NOT_IMPLEMENTED = 5,
  /*
   * Not supported
   */
  CIOT__CIOT_ERR__CIOT_ERR_NOT_SUPPORTED = 6,
  /*
   * Busy
   */
  CIOT__CIOT_ERR__CIOT_ERR_BUSY = 7,
  /*
   * Invalid state
   */
  CIOT__CIOT_ERR__CIOT_ERR_INVALID_STATE = 8,
  /*
   * Serialization error
   */
  CIOT__CIOT_ERR__CIOT_ERR_SERIALIZATION = 9,
  /*
   * Deserialization error
   */
  CIOT__CIOT_ERR__CIOT_ERR_DESERIALIZATION = 10,
  /*
   * Error sending data
   */
  CIOT__CIOT_ERR__CIOT_ERR_SEND_DATA = 11,
  /*
   * Error on data receive
   */
  CIOT__CIOT_ERR__CIOT_ERR_RECV_DATA = 12,
  /*
   * Invalid size
   */
  CIOT__CIOT_ERR__CIOT_ERR_INVALID_SIZE = 13,
  /*
   * Closed
   */
  CIOT__CIOT_ERR__CIOT_ERR_CLOSED = 14,
  /*
   * Resource not found
   */
  CIOT__CIOT_ERR__CIOT_ERR_NOT_FOUND = 15,
  /*
   * Validation failed
   */
  CIOT__CIOT_ERR__CIOT_ERR_VALIDATION_FAILED = 16,
  /*
   * Connection failed
   */
  CIOT__CIOT_ERR__CIOT_ERR_CONNECTION = 17,
  /*
   * Disconnection failed
   */
  CIOT__CIOT_ERR__CIOT_ERR_DISCONNECTION = 18,
  /*
   * Unknown exception occours
   */
  CIOT__CIOT_ERR__CIOT_ERR_EXCEPTION = 19,
  /*
   * Terminator is missing
   */
  CIOT__CIOT_ERR__CIOT_ERR_TERMINATOR_MISSING = 20,
  /*
   * Invalid argument detected
   */
  CIOT__CIOT_ERR__CIOT_ERR_INVALID_ARG = 21,
  /*
   * Insuficient memory
   */
  CIOT__CIOT_ERR__CIOT_ERR_NO_MEMORY = 22,
  /*
   * Timeout
   */
  CIOT__CIOT_ERR__CIOT_ERR_TIMEOUT = 23,
  /*
   * Operation failed
   */
  CIOT__CIOT_ERR__CIOT_FAIL = -1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CIOT__CIOT_ERR)
} Ciot__CiotErr;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    ciot__ciot_err__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ciot_2fproto_2fv1_2ferrors_2eproto__INCLUDED */
