/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ciot/proto/v1/gpio.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ciot/proto/v1/gpio.pb-c.h"
void   ciot__gpio_cfg__init
                     (Ciot__GpioCfg         *message)
{
  static const Ciot__GpioCfg init_value = CIOT__GPIO_CFG__INIT;
  *message = init_value;
}
size_t ciot__gpio_cfg__get_packed_size
                     (const Ciot__GpioCfg *message)
{
  assert(message->base.descriptor == &ciot__gpio_cfg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__gpio_cfg__pack
                     (const Ciot__GpioCfg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__gpio_cfg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__gpio_cfg__pack_to_buffer
                     (const Ciot__GpioCfg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__gpio_cfg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__GpioCfg *
       ciot__gpio_cfg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__GpioCfg *)
     protobuf_c_message_unpack (&ciot__gpio_cfg__descriptor,
                                allocator, len, data);
}
void   ciot__gpio_cfg__free_unpacked
                     (Ciot__GpioCfg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__gpio_cfg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__gpio_status__init
                     (Ciot__GpioStatus         *message)
{
  static const Ciot__GpioStatus init_value = CIOT__GPIO_STATUS__INIT;
  *message = init_value;
}
size_t ciot__gpio_status__get_packed_size
                     (const Ciot__GpioStatus *message)
{
  assert(message->base.descriptor == &ciot__gpio_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__gpio_status__pack
                     (const Ciot__GpioStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__gpio_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__gpio_status__pack_to_buffer
                     (const Ciot__GpioStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__gpio_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__GpioStatus *
       ciot__gpio_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__GpioStatus *)
     protobuf_c_message_unpack (&ciot__gpio_status__descriptor,
                                allocator, len, data);
}
void   ciot__gpio_status__free_unpacked
                     (Ciot__GpioStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__gpio_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__gpio_state_info__init
                     (Ciot__GpioStateInfo         *message)
{
  static const Ciot__GpioStateInfo init_value = CIOT__GPIO_STATE_INFO__INIT;
  *message = init_value;
}
size_t ciot__gpio_state_info__get_packed_size
                     (const Ciot__GpioStateInfo *message)
{
  assert(message->base.descriptor == &ciot__gpio_state_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__gpio_state_info__pack
                     (const Ciot__GpioStateInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__gpio_state_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__gpio_state_info__pack_to_buffer
                     (const Ciot__GpioStateInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__gpio_state_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__GpioStateInfo *
       ciot__gpio_state_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__GpioStateInfo *)
     protobuf_c_message_unpack (&ciot__gpio_state_info__descriptor,
                                allocator, len, data);
}
void   ciot__gpio_state_info__free_unpacked
                     (Ciot__GpioStateInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__gpio_state_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__gpio_req__init
                     (Ciot__GpioReq         *message)
{
  static const Ciot__GpioReq init_value = CIOT__GPIO_REQ__INIT;
  *message = init_value;
}
size_t ciot__gpio_req__get_packed_size
                     (const Ciot__GpioReq *message)
{
  assert(message->base.descriptor == &ciot__gpio_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__gpio_req__pack
                     (const Ciot__GpioReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__gpio_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__gpio_req__pack_to_buffer
                     (const Ciot__GpioReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__gpio_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__GpioReq *
       ciot__gpio_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__GpioReq *)
     protobuf_c_message_unpack (&ciot__gpio_req__descriptor,
                                allocator, len, data);
}
void   ciot__gpio_req__free_unpacked
                     (Ciot__GpioReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__gpio_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__gpio_data__init
                     (Ciot__GpioData         *message)
{
  static const Ciot__GpioData init_value = CIOT__GPIO_DATA__INIT;
  *message = init_value;
}
size_t ciot__gpio_data__get_packed_size
                     (const Ciot__GpioData *message)
{
  assert(message->base.descriptor == &ciot__gpio_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__gpio_data__pack
                     (const Ciot__GpioData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__gpio_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__gpio_data__pack_to_buffer
                     (const Ciot__GpioData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__gpio_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__GpioData *
       ciot__gpio_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__GpioData *)
     protobuf_c_message_unpack (&ciot__gpio_data__descriptor,
                                allocator, len, data);
}
void   ciot__gpio_data__free_unpacked
                     (Ciot__GpioData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__gpio_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ciot__gpio_cfg__field_descriptors[4] =
{
  {
    "pins",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioCfg, pins),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modes",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioCfg, modes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pull",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioCfg, pull),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blink_interval",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioCfg, blink_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__gpio_cfg__field_indices_by_name[] = {
  3,   /* field[3] = blink_interval */
  1,   /* field[1] = modes */
  0,   /* field[0] = pins */
  2,   /* field[2] = pull */
};
static const ProtobufCIntRange ciot__gpio_cfg__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ciot__gpio_cfg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.GpioCfg",
  "GpioCfg",
  "Ciot__GpioCfg",
  "Ciot",
  sizeof(Ciot__GpioCfg),
  4,
  ciot__gpio_cfg__field_descriptors,
  ciot__gpio_cfg__field_indices_by_name,
  2,  ciot__gpio_cfg__number_ranges,
  (ProtobufCMessageInit) ciot__gpio_cfg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__gpio_status__field_descriptors[1] =
{
  {
    "states",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioStatus, states),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__gpio_status__field_indices_by_name[] = {
  0,   /* field[0] = states */
};
static const ProtobufCIntRange ciot__gpio_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ciot__gpio_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.GpioStatus",
  "GpioStatus",
  "Ciot__GpioStatus",
  "Ciot",
  sizeof(Ciot__GpioStatus),
  1,
  ciot__gpio_status__field_descriptors,
  ciot__gpio_status__field_indices_by_name,
  1,  ciot__gpio_status__number_ranges,
  (ProtobufCMessageInit) ciot__gpio_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__gpio_state_info__field_descriptors[2] =
{
  {
    "num",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioStateInfo, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioStateInfo, state),
    &ciot__gpio_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__gpio_state_info__field_indices_by_name[] = {
  0,   /* field[0] = num */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange ciot__gpio_state_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ciot__gpio_state_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.GpioStateInfo",
  "GpioStateInfo",
  "Ciot__GpioStateInfo",
  "Ciot",
  sizeof(Ciot__GpioStateInfo),
  2,
  ciot__gpio_state_info__field_descriptors,
  ciot__gpio_state_info__field_indices_by_name,
  1,  ciot__gpio_state_info__number_ranges,
  (ProtobufCMessageInit) ciot__gpio_state_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__gpio_req__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioReq, type),
    &ciot__gpio_req_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "config",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioReq, config),
    &ciot__gpio_cfg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioReq, status),
    &ciot__gpio_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioReq, state),
    &ciot__gpio_state_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__gpio_req__field_indices_by_name[] = {
  1,   /* field[1] = config */
  3,   /* field[3] = state */
  2,   /* field[2] = status */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ciot__gpio_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ciot__gpio_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.GpioReq",
  "GpioReq",
  "Ciot__GpioReq",
  "Ciot",
  sizeof(Ciot__GpioReq),
  4,
  ciot__gpio_req__field_descriptors,
  ciot__gpio_req__field_indices_by_name,
  1,  ciot__gpio_req__number_ranges,
  (ProtobufCMessageInit) ciot__gpio_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__gpio_data__field_descriptors[3] =
{
  {
    "config",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioData, config),
    &ciot__gpio_cfg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioData, status),
    &ciot__gpio_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__GpioData, request),
    &ciot__gpio_req__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__gpio_data__field_indices_by_name[] = {
  0,   /* field[0] = config */
  2,   /* field[2] = request */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ciot__gpio_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ciot__gpio_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.GpioData",
  "GpioData",
  "Ciot__GpioData",
  "Ciot",
  sizeof(Ciot__GpioData),
  3,
  ciot__gpio_data__field_descriptors,
  ciot__gpio_data__field_indices_by_name,
  1,  ciot__gpio_data__number_ranges,
  (ProtobufCMessageInit) ciot__gpio_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ciot__gpio_state__enum_values_by_number[6] =
{
  { "GPIO_STATE_LOW", "CIOT__GPIO_STATE__GPIO_STATE_LOW", 0 },
  { "GPIO_STATE_HIGH", "CIOT__GPIO_STATE__GPIO_STATE_HIGH", 1 },
  { "GPIO_STATE_BLINK", "CIOT__GPIO_STATE__GPIO_STATE_BLINK", 2 },
  { "GPIO_STATE_BLINKED", "CIOT__GPIO_STATE__GPIO_STATE_BLINKED", 3 },
  { "GPIO_STATE_BLINKING", "CIOT__GPIO_STATE__GPIO_STATE_BLINKING", 4 },
  { "GPIO_STATE_ERROR", "CIOT__GPIO_STATE__GPIO_STATE_ERROR", 5 },
};
static const ProtobufCIntRange ciot__gpio_state__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex ciot__gpio_state__enum_values_by_name[6] =
{
  { "GPIO_STATE_BLINK", 2 },
  { "GPIO_STATE_BLINKED", 3 },
  { "GPIO_STATE_BLINKING", 4 },
  { "GPIO_STATE_ERROR", 5 },
  { "GPIO_STATE_HIGH", 1 },
  { "GPIO_STATE_LOW", 0 },
};
const ProtobufCEnumDescriptor ciot__gpio_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.GpioState",
  "GpioState",
  "Ciot__GpioState",
  "Ciot",
  6,
  ciot__gpio_state__enum_values_by_number,
  6,
  ciot__gpio_state__enum_values_by_name,
  1,
  ciot__gpio_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ciot__gpio_req_type__enum_values_by_number[6] =
{
  { "GPIO_REQ_TYPE_UNKNOWN", "CIOT__GPIO_REQ_TYPE__GPIO_REQ_TYPE_UNKNOWN", 0 },
  { "GPIO_REQ_TYPE_CONFIG", "CIOT__GPIO_REQ_TYPE__GPIO_REQ_TYPE_CONFIG", 1 },
  { "GPIO_REQ_TYPE_SET_STATUS", "CIOT__GPIO_REQ_TYPE__GPIO_REQ_TYPE_SET_STATUS", 2 },
  { "GPIO_REQ_TYPE_SET_STATE", "CIOT__GPIO_REQ_TYPE__GPIO_REQ_TYPE_SET_STATE", 3 },
  { "GPIO_REQ_TYPE_GET_STATUS", "CIOT__GPIO_REQ_TYPE__GPIO_REQ_TYPE_GET_STATUS", 4 },
  { "GPIO_REQ_TYPE_GET_STATE", "CIOT__GPIO_REQ_TYPE__GPIO_REQ_TYPE_GET_STATE", 5 },
};
static const ProtobufCIntRange ciot__gpio_req_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex ciot__gpio_req_type__enum_values_by_name[6] =
{
  { "GPIO_REQ_TYPE_CONFIG", 1 },
  { "GPIO_REQ_TYPE_GET_STATE", 5 },
  { "GPIO_REQ_TYPE_GET_STATUS", 4 },
  { "GPIO_REQ_TYPE_SET_STATE", 3 },
  { "GPIO_REQ_TYPE_SET_STATUS", 2 },
  { "GPIO_REQ_TYPE_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor ciot__gpio_req_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.GpioReqType",
  "GpioReqType",
  "Ciot__GpioReqType",
  "Ciot",
  6,
  ciot__gpio_req_type__enum_values_by_number,
  6,
  ciot__gpio_req_type__enum_values_by_name,
  1,
  ciot__gpio_req_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ciot__gpio_mode__enum_values_by_number[3] =
{
  { "GPIO_MODE_DISABLED", "CIOT__GPIO_MODE__GPIO_MODE_DISABLED", 0 },
  { "GPIO_MODE_INPUT", "CIOT__GPIO_MODE__GPIO_MODE_INPUT", 1 },
  { "GPIO_MODE_OUTPUT", "CIOT__GPIO_MODE__GPIO_MODE_OUTPUT", 2 },
};
static const ProtobufCIntRange ciot__gpio_mode__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ciot__gpio_mode__enum_values_by_name[3] =
{
  { "GPIO_MODE_DISABLED", 0 },
  { "GPIO_MODE_INPUT", 1 },
  { "GPIO_MODE_OUTPUT", 2 },
};
const ProtobufCEnumDescriptor ciot__gpio_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.GpioMode",
  "GpioMode",
  "Ciot__GpioMode",
  "Ciot",
  3,
  ciot__gpio_mode__enum_values_by_number,
  3,
  ciot__gpio_mode__enum_values_by_name,
  1,
  ciot__gpio_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ciot__gpio_pull__enum_values_by_number[3] =
{
  { "GPIO_PULL_DISABLED", "CIOT__GPIO_PULL__GPIO_PULL_DISABLED", 0 },
  { "GPIO_PULL_UP", "CIOT__GPIO_PULL__GPIO_PULL_UP", 1 },
  { "GPIO_PULL_DOWN", "CIOT__GPIO_PULL__GPIO_PULL_DOWN", 2 },
};
static const ProtobufCIntRange ciot__gpio_pull__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ciot__gpio_pull__enum_values_by_name[3] =
{
  { "GPIO_PULL_DISABLED", 0 },
  { "GPIO_PULL_DOWN", 2 },
  { "GPIO_PULL_UP", 1 },
};
const ProtobufCEnumDescriptor ciot__gpio_pull__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.GpioPull",
  "GpioPull",
  "Ciot__GpioPull",
  "Ciot",
  3,
  ciot__gpio_pull__enum_values_by_number,
  3,
  ciot__gpio_pull__enum_values_by_name,
  1,
  ciot__gpio_pull__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
