/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ciot/proto/v1/ntp.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ciot/proto/v1/ntp.pb-c.h"
void   ciot__ntp_cfg__init
                     (Ciot__NtpCfg         *message)
{
  static const Ciot__NtpCfg init_value = CIOT__NTP_CFG__INIT;
  *message = init_value;
}
size_t ciot__ntp_cfg__get_packed_size
                     (const Ciot__NtpCfg *message)
{
  assert(message->base.descriptor == &ciot__ntp_cfg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__ntp_cfg__pack
                     (const Ciot__NtpCfg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__ntp_cfg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__ntp_cfg__pack_to_buffer
                     (const Ciot__NtpCfg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__ntp_cfg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__NtpCfg *
       ciot__ntp_cfg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__NtpCfg *)
     protobuf_c_message_unpack (&ciot__ntp_cfg__descriptor,
                                allocator, len, data);
}
void   ciot__ntp_cfg__free_unpacked
                     (Ciot__NtpCfg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__ntp_cfg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__ntp_status__init
                     (Ciot__NtpStatus         *message)
{
  static const Ciot__NtpStatus init_value = CIOT__NTP_STATUS__INIT;
  *message = init_value;
}
size_t ciot__ntp_status__get_packed_size
                     (const Ciot__NtpStatus *message)
{
  assert(message->base.descriptor == &ciot__ntp_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__ntp_status__pack
                     (const Ciot__NtpStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__ntp_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__ntp_status__pack_to_buffer
                     (const Ciot__NtpStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__ntp_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__NtpStatus *
       ciot__ntp_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__NtpStatus *)
     protobuf_c_message_unpack (&ciot__ntp_status__descriptor,
                                allocator, len, data);
}
void   ciot__ntp_status__free_unpacked
                     (Ciot__NtpStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__ntp_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__ntp_req_data__init
                     (Ciot__NtpReqData         *message)
{
  static const Ciot__NtpReqData init_value = CIOT__NTP_REQ_DATA__INIT;
  *message = init_value;
}
size_t ciot__ntp_req_data__get_packed_size
                     (const Ciot__NtpReqData *message)
{
  assert(message->base.descriptor == &ciot__ntp_req_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__ntp_req_data__pack
                     (const Ciot__NtpReqData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__ntp_req_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__ntp_req_data__pack_to_buffer
                     (const Ciot__NtpReqData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__ntp_req_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__NtpReqData *
       ciot__ntp_req_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__NtpReqData *)
     protobuf_c_message_unpack (&ciot__ntp_req_data__descriptor,
                                allocator, len, data);
}
void   ciot__ntp_req_data__free_unpacked
                     (Ciot__NtpReqData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__ntp_req_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__ntp_req__init
                     (Ciot__NtpReq         *message)
{
  static const Ciot__NtpReq init_value = CIOT__NTP_REQ__INIT;
  *message = init_value;
}
size_t ciot__ntp_req__get_packed_size
                     (const Ciot__NtpReq *message)
{
  assert(message->base.descriptor == &ciot__ntp_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__ntp_req__pack
                     (const Ciot__NtpReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__ntp_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__ntp_req__pack_to_buffer
                     (const Ciot__NtpReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__ntp_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__NtpReq *
       ciot__ntp_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__NtpReq *)
     protobuf_c_message_unpack (&ciot__ntp_req__descriptor,
                                allocator, len, data);
}
void   ciot__ntp_req__free_unpacked
                     (Ciot__NtpReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__ntp_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__ntp_data__init
                     (Ciot__NtpData         *message)
{
  static const Ciot__NtpData init_value = CIOT__NTP_DATA__INIT;
  *message = init_value;
}
size_t ciot__ntp_data__get_packed_size
                     (const Ciot__NtpData *message)
{
  assert(message->base.descriptor == &ciot__ntp_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__ntp_data__pack
                     (const Ciot__NtpData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__ntp_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__ntp_data__pack_to_buffer
                     (const Ciot__NtpData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__ntp_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__NtpData *
       ciot__ntp_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__NtpData *)
     protobuf_c_message_unpack (&ciot__ntp_data__descriptor,
                                allocator, len, data);
}
void   ciot__ntp_data__free_unpacked
                     (Ciot__NtpData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__ntp_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ciot__ntp_cfg__field_descriptors[7] =
{
  {
    "op_mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpCfg, op_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync_mode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpCfg, sync_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync_interval",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpCfg, sync_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timezone",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpCfg, timezone),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server1",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpCfg, server1),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server2",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpCfg, server2),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server3",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpCfg, server3),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__ntp_cfg__field_indices_by_name[] = {
  0,   /* field[0] = op_mode */
  4,   /* field[4] = server1 */
  5,   /* field[5] = server2 */
  6,   /* field[6] = server3 */
  2,   /* field[2] = sync_interval */
  1,   /* field[1] = sync_mode */
  3,   /* field[3] = timezone */
};
static const ProtobufCIntRange ciot__ntp_cfg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ciot__ntp_cfg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.NtpCfg",
  "NtpCfg",
  "Ciot__NtpCfg",
  "Ciot",
  sizeof(Ciot__NtpCfg),
  7,
  ciot__ntp_cfg__field_descriptors,
  ciot__ntp_cfg__field_indices_by_name,
  1,  ciot__ntp_cfg__number_ranges,
  (ProtobufCMessageInit) ciot__ntp_cfg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__ntp_status__field_descriptors[5] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpStatus, state),
    &ciot__ntp_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_sync",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpStatus, last_sync),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync_count",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpStatus, sync_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "init",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpStatus, init),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sync",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpStatus, sync),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__ntp_status__field_indices_by_name[] = {
  3,   /* field[3] = init */
  1,   /* field[1] = last_sync */
  0,   /* field[0] = state */
  4,   /* field[4] = sync */
  2,   /* field[2] = sync_count */
};
static const ProtobufCIntRange ciot__ntp_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ciot__ntp_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.NtpStatus",
  "NtpStatus",
  "Ciot__NtpStatus",
  "Ciot",
  sizeof(Ciot__NtpStatus),
  5,
  ciot__ntp_status__field_descriptors,
  ciot__ntp_status__field_indices_by_name,
  1,  ciot__ntp_status__number_ranges,
  (ProtobufCMessageInit) ciot__ntp_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define ciot__ntp_req_data__field_descriptors NULL
#define ciot__ntp_req_data__field_indices_by_name NULL
#define ciot__ntp_req_data__number_ranges NULL
const ProtobufCMessageDescriptor ciot__ntp_req_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.NtpReqData",
  "NtpReqData",
  "Ciot__NtpReqData",
  "Ciot",
  sizeof(Ciot__NtpReqData),
  0,
  ciot__ntp_req_data__field_descriptors,
  ciot__ntp_req_data__field_indices_by_name,
  0,  ciot__ntp_req_data__number_ranges,
  (ProtobufCMessageInit) ciot__ntp_req_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__ntp_req__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpReq, type),
    &ciot__ntp_req_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpReq, data),
    &ciot__ntp_req_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__ntp_req__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ciot__ntp_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ciot__ntp_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.NtpReq",
  "NtpReq",
  "Ciot__NtpReq",
  "Ciot",
  sizeof(Ciot__NtpReq),
  2,
  ciot__ntp_req__field_descriptors,
  ciot__ntp_req__field_indices_by_name,
  1,  ciot__ntp_req__number_ranges,
  (ProtobufCMessageInit) ciot__ntp_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__ntp_data__field_descriptors[3] =
{
  {
    "config",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpData, config),
    &ciot__ntp_cfg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpData, status),
    &ciot__ntp_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__NtpData, request),
    &ciot__ntp_req__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__ntp_data__field_indices_by_name[] = {
  0,   /* field[0] = config */
  2,   /* field[2] = request */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ciot__ntp_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ciot__ntp_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.NtpData",
  "NtpData",
  "Ciot__NtpData",
  "Ciot",
  sizeof(Ciot__NtpData),
  3,
  ciot__ntp_data__field_descriptors,
  ciot__ntp_data__field_indices_by_name,
  1,  ciot__ntp_data__number_ranges,
  (ProtobufCMessageInit) ciot__ntp_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ciot__ntp_state__enum_values_by_number[3] =
{
  { "NTP_STATE_RESET", "CIOT__NTP_STATE__NTP_STATE_RESET", 0 },
  { "NTP_STATE_COMPLETED", "CIOT__NTP_STATE__NTP_STATE_COMPLETED", 1 },
  { "NTP_STATE_IN_PROGRESS", "CIOT__NTP_STATE__NTP_STATE_IN_PROGRESS", 2 },
};
static const ProtobufCIntRange ciot__ntp_state__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ciot__ntp_state__enum_values_by_name[3] =
{
  { "NTP_STATE_COMPLETED", 1 },
  { "NTP_STATE_IN_PROGRESS", 2 },
  { "NTP_STATE_RESET", 0 },
};
const ProtobufCEnumDescriptor ciot__ntp_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.NtpState",
  "NtpState",
  "Ciot__NtpState",
  "Ciot",
  3,
  ciot__ntp_state__enum_values_by_number,
  3,
  ciot__ntp_state__enum_values_by_name,
  1,
  ciot__ntp_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ciot__ntp_req_type__enum_values_by_number[1] =
{
  { "NTP_REQ_TYPE_UNKOWN", "CIOT__NTP_REQ_TYPE__NTP_REQ_TYPE_UNKOWN", 0 },
};
static const ProtobufCIntRange ciot__ntp_req_type__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex ciot__ntp_req_type__enum_values_by_name[1] =
{
  { "NTP_REQ_TYPE_UNKOWN", 0 },
};
const ProtobufCEnumDescriptor ciot__ntp_req_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.NtpReqType",
  "NtpReqType",
  "Ciot__NtpReqType",
  "Ciot",
  1,
  ciot__ntp_req_type__enum_values_by_number,
  1,
  ciot__ntp_req_type__enum_values_by_name,
  1,
  ciot__ntp_req_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
