/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ciot/proto/v1/storage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ciot/proto/v1/storage.pb-c.h"
void   ciot__storage_cfg__init
                     (Ciot__StorageCfg         *message)
{
  static const Ciot__StorageCfg init_value = CIOT__STORAGE_CFG__INIT;
  *message = init_value;
}
size_t ciot__storage_cfg__get_packed_size
                     (const Ciot__StorageCfg *message)
{
  assert(message->base.descriptor == &ciot__storage_cfg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__storage_cfg__pack
                     (const Ciot__StorageCfg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__storage_cfg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__storage_cfg__pack_to_buffer
                     (const Ciot__StorageCfg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__storage_cfg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__StorageCfg *
       ciot__storage_cfg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__StorageCfg *)
     protobuf_c_message_unpack (&ciot__storage_cfg__descriptor,
                                allocator, len, data);
}
void   ciot__storage_cfg__free_unpacked
                     (Ciot__StorageCfg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__storage_cfg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__storage_status__init
                     (Ciot__StorageStatus         *message)
{
  static const Ciot__StorageStatus init_value = CIOT__STORAGE_STATUS__INIT;
  *message = init_value;
}
size_t ciot__storage_status__get_packed_size
                     (const Ciot__StorageStatus *message)
{
  assert(message->base.descriptor == &ciot__storage_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__storage_status__pack
                     (const Ciot__StorageStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__storage_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__storage_status__pack_to_buffer
                     (const Ciot__StorageStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__storage_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__StorageStatus *
       ciot__storage_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__StorageStatus *)
     protobuf_c_message_unpack (&ciot__storage_status__descriptor,
                                allocator, len, data);
}
void   ciot__storage_status__free_unpacked
                     (Ciot__StorageStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__storage_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__storage_req_data__init
                     (Ciot__StorageReqData         *message)
{
  static const Ciot__StorageReqData init_value = CIOT__STORAGE_REQ_DATA__INIT;
  *message = init_value;
}
size_t ciot__storage_req_data__get_packed_size
                     (const Ciot__StorageReqData *message)
{
  assert(message->base.descriptor == &ciot__storage_req_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__storage_req_data__pack
                     (const Ciot__StorageReqData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__storage_req_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__storage_req_data__pack_to_buffer
                     (const Ciot__StorageReqData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__storage_req_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__StorageReqData *
       ciot__storage_req_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__StorageReqData *)
     protobuf_c_message_unpack (&ciot__storage_req_data__descriptor,
                                allocator, len, data);
}
void   ciot__storage_req_data__free_unpacked
                     (Ciot__StorageReqData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__storage_req_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__storage_req__init
                     (Ciot__StorageReq         *message)
{
  static const Ciot__StorageReq init_value = CIOT__STORAGE_REQ__INIT;
  *message = init_value;
}
size_t ciot__storage_req__get_packed_size
                     (const Ciot__StorageReq *message)
{
  assert(message->base.descriptor == &ciot__storage_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__storage_req__pack
                     (const Ciot__StorageReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__storage_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__storage_req__pack_to_buffer
                     (const Ciot__StorageReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__storage_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__StorageReq *
       ciot__storage_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__StorageReq *)
     protobuf_c_message_unpack (&ciot__storage_req__descriptor,
                                allocator, len, data);
}
void   ciot__storage_req__free_unpacked
                     (Ciot__StorageReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__storage_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__storage_data__init
                     (Ciot__StorageData         *message)
{
  static const Ciot__StorageData init_value = CIOT__STORAGE_DATA__INIT;
  *message = init_value;
}
size_t ciot__storage_data__get_packed_size
                     (const Ciot__StorageData *message)
{
  assert(message->base.descriptor == &ciot__storage_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__storage_data__pack
                     (const Ciot__StorageData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__storage_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__storage_data__pack_to_buffer
                     (const Ciot__StorageData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__storage_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__StorageData *
       ciot__storage_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__StorageData *)
     protobuf_c_message_unpack (&ciot__storage_data__descriptor,
                                allocator, len, data);
}
void   ciot__storage_data__free_unpacked
                     (Ciot__StorageData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__storage_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ciot__storage_cfg__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__StorageCfg, type),
    &ciot__storage_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__storage_cfg__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ciot__storage_cfg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ciot__storage_cfg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.StorageCfg",
  "StorageCfg",
  "Ciot__StorageCfg",
  "Ciot",
  sizeof(Ciot__StorageCfg),
  1,
  ciot__storage_cfg__field_descriptors,
  ciot__storage_cfg__field_indices_by_name,
  1,  ciot__storage_cfg__number_ranges,
  (ProtobufCMessageInit) ciot__storage_cfg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__storage_status__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__StorageStatus, state),
    &ciot__storage_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__storage_status__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange ciot__storage_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ciot__storage_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.StorageStatus",
  "StorageStatus",
  "Ciot__StorageStatus",
  "Ciot",
  sizeof(Ciot__StorageStatus),
  1,
  ciot__storage_status__field_descriptors,
  ciot__storage_status__field_indices_by_name,
  1,  ciot__storage_status__number_ranges,
  (ProtobufCMessageInit) ciot__storage_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__storage_req_data__field_descriptors[2] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ciot__StorageReqData, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Ciot__StorageReqData, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__storage_req_data__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = path */
};
static const ProtobufCIntRange ciot__storage_req_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ciot__storage_req_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.StorageReqData",
  "StorageReqData",
  "Ciot__StorageReqData",
  "Ciot",
  sizeof(Ciot__StorageReqData),
  2,
  ciot__storage_req_data__field_descriptors,
  ciot__storage_req_data__field_indices_by_name,
  1,  ciot__storage_req_data__number_ranges,
  (ProtobufCMessageInit) ciot__storage_req_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__storage_req__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__StorageReq, type),
    &ciot__storage_req_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__StorageReq, data),
    &ciot__storage_req_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__storage_req__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ciot__storage_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ciot__storage_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.StorageReq",
  "StorageReq",
  "Ciot__StorageReq",
  "Ciot",
  sizeof(Ciot__StorageReq),
  2,
  ciot__storage_req__field_descriptors,
  ciot__storage_req__field_indices_by_name,
  1,  ciot__storage_req__number_ranges,
  (ProtobufCMessageInit) ciot__storage_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__storage_data__field_descriptors[3] =
{
  {
    "config",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__StorageData, config),
    &ciot__storage_cfg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__StorageData, status),
    &ciot__storage_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__StorageData, request),
    &ciot__storage_req__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__storage_data__field_indices_by_name[] = {
  0,   /* field[0] = config */
  2,   /* field[2] = request */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange ciot__storage_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ciot__storage_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.StorageData",
  "StorageData",
  "Ciot__StorageData",
  "Ciot",
  sizeof(Ciot__StorageData),
  3,
  ciot__storage_data__field_descriptors,
  ciot__storage_data__field_indices_by_name,
  1,  ciot__storage_data__number_ranges,
  (ProtobufCMessageInit) ciot__storage_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ciot__storage_state__enum_values_by_number[1] =
{
  { "STORAGE_STATE_IDLE", "CIOT__STORAGE_STATE__STORAGE_STATE_IDLE", 0 },
};
static const ProtobufCIntRange ciot__storage_state__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex ciot__storage_state__enum_values_by_name[1] =
{
  { "STORAGE_STATE_IDLE", 0 },
};
const ProtobufCEnumDescriptor ciot__storage_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.StorageState",
  "StorageState",
  "Ciot__StorageState",
  "Ciot",
  1,
  ciot__storage_state__enum_values_by_number,
  1,
  ciot__storage_state__enum_values_by_name,
  1,
  ciot__storage_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ciot__storage_req_type__enum_values_by_number[5] =
{
  { "STORAGE_REQ_TYPE_UNKOWN", "CIOT__STORAGE_REQ_TYPE__STORAGE_REQ_TYPE_UNKOWN", 0 },
  { "STORAGE_REQ_TYPE_REQ_SAVE", "CIOT__STORAGE_REQ_TYPE__STORAGE_REQ_TYPE_REQ_SAVE", 1 },
  { "STORAGE_REQ_TYPE_REQ_LOAD", "CIOT__STORAGE_REQ_TYPE__STORAGE_REQ_TYPE_REQ_LOAD", 2 },
  { "STORAGE_REQ_TYPE_REQ_DELETE", "CIOT__STORAGE_REQ_TYPE__STORAGE_REQ_TYPE_REQ_DELETE", 3 },
  { "STORAGE_REQ_TYPE_REQ_FORMAT", "CIOT__STORAGE_REQ_TYPE__STORAGE_REQ_TYPE_REQ_FORMAT", 4 },
};
static const ProtobufCIntRange ciot__storage_req_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex ciot__storage_req_type__enum_values_by_name[5] =
{
  { "STORAGE_REQ_TYPE_REQ_DELETE", 3 },
  { "STORAGE_REQ_TYPE_REQ_FORMAT", 4 },
  { "STORAGE_REQ_TYPE_REQ_LOAD", 2 },
  { "STORAGE_REQ_TYPE_REQ_SAVE", 1 },
  { "STORAGE_REQ_TYPE_UNKOWN", 0 },
};
const ProtobufCEnumDescriptor ciot__storage_req_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.StorageReqType",
  "StorageReqType",
  "Ciot__StorageReqType",
  "Ciot",
  5,
  ciot__storage_req_type__enum_values_by_number,
  5,
  ciot__storage_req_type__enum_values_by_name,
  1,
  ciot__storage_req_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ciot__storage_type__enum_values_by_number[4] =
{
  { "STORAGE_TYPE_UNKNOWN", "CIOT__STORAGE_TYPE__STORAGE_TYPE_UNKNOWN", 0 },
  { "STORAGE_TYPE_EEPROM", "CIOT__STORAGE_TYPE__STORAGE_TYPE_EEPROM", 1 },
  { "STORAGE_TYPE_FLASH", "CIOT__STORAGE_TYPE__STORAGE_TYPE_FLASH", 2 },
  { "STORAGE_TYPE_FS", "CIOT__STORAGE_TYPE__STORAGE_TYPE_FS", 3 },
};
static const ProtobufCIntRange ciot__storage_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex ciot__storage_type__enum_values_by_name[4] =
{
  { "STORAGE_TYPE_EEPROM", 1 },
  { "STORAGE_TYPE_FLASH", 2 },
  { "STORAGE_TYPE_FS", 3 },
  { "STORAGE_TYPE_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor ciot__storage_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.StorageType",
  "StorageType",
  "Ciot__StorageType",
  "Ciot",
  4,
  ciot__storage_type__enum_values_by_number,
  4,
  ciot__storage_type__enum_values_by_name,
  1,
  ciot__storage_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
