set(CIOT_DIR F:/projects/ciot-platform/ciot_c)

set(CIOT_INCLUDE_DIRS
    ${CIOT_DIR}/include/types
    ${CIOT_DIR}/include
    ${CIOT_DIR}/src/mg
)

set(PROTOBUF_C_DIR ${CIOT_DIR}/src/proto/protobuf-c)

set(PROTO_INCLUDE_DIRS
    ${PROTOBUF_C_DIR}
    ${CIOT_DIR}/src/proto
)

set(CIOT_OPCUA_INCLUDE_DIR ${CIOT_DIR}/src/opcua)

FILE(GLOB_RECURSE PROTOBUF_C ${PROTOBUF_C_DIR}/protobuf-c/*.c)
FILE(GLOB_RECURSE PROTO_CIOT ${CIOT_DIR}/src/proto/*.c)

FILE(GLOB_RECURSE CIOT_UNSUPPORTED_SRCS ${CIOT_DIR}/src/unsupported/*.c)
FILE(GLOB_RECURSE CIOT_COMMON_SRCS ${CIOT_DIR}/src/common/*.c)
FILE(GLOB_RECURSE CIOT_ESP32_SRCS ${CIOT_DIR}/src/esp32/*.c)
FILE(GLOB_RECURSE CIOT_MONGOOSE_SRCS ${CIOT_DIR}/src/mg/*.c)
FILE(GLOB_RECURSE CIOT_WIN_SRCS ${CIOT_DIR}/src/win/*.c)
FILE(GLOB_RECURSE CIOT_LINUX_SRCS ${CIOT_DIR}/src/linux/*.c)
FILE(GLOB_RECURSE CIOT_OPCUA_SRCS ${CIOT_OPCUA_INCLUDE_DIR}/*.c)

list(APPEND PROTO_SRCS ${PROTOBUF_C})
list(APPEND PROTO_SRCS ${PROTO_CIOT})

# list(APPEND CIOT_ESP32_SRCS ${CIOT_ESP32_SRCS})
list(APPEND CIOT_ESP32_SRCS ${CIOT_COMMON_SRCS})

list(APPEND CIOT_PC_SRCS ${CIOT_UNSUPPORTED_SRCS})
list(APPEND CIOT_PC_SRCS ${CIOT_COMMON_SRCS})
list(APPEND CIOT_PC_SRCS ${CIOT_MONGOOSE_SRCS})

if (UNIX)
    list(APPEND CIOT_PC_SRCS ${CIOT_LINUX_SRCS})
else()
    list(APPEND CIOT_PC_SRCS ${CIOT_WIN_SRCS})
endif()
