/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ciot/proto/v2/errors.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CIOT_ERR_DATA, ciot_err_data_t, AUTO)





