/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_CIOT_CIOT_PROTO_V2_ERRORS_PB_H_INCLUDED
#define PB_CIOT_CIOT_PROTO_V2_ERRORS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Error codes */
typedef enum ciot_err {
    CIOT_ERR_OK = 0, /* No error */
    CIOT_ERR_NULL_ARG = 1, /* Null argunment */
    CIOT_ERR_INVALID_ID = 2, /* Invalid ID */
    CIOT_ERR_INVALID_TYPE = 3, /* Invalid Type */
    CIOT_ERR_OVERFLOW = 4, /* Memory overflow */
    CIOT_ERR_NOT_IMPLEMENTED = 5, /* Not implemented */
    CIOT_ERR_NOT_SUPPORTED = 6, /* Not supported */
    CIOT_ERR_BUSY = 7, /* Busy */
    CIOT_ERR_INVALID_STATE = 8, /* Invalid state */
    CIOT_ERR_SERIALIZATION = 9, /* Serialization error */
    CIOT_ERR_DESERIALIZATION = 10, /* Deserialization error */
    CIOT_ERR_SEND_DATA = 11, /* Error sending data */
    CIOT_ERR_RECV_DATA = 12, /* Error on data receive */
    CIOT_ERR_INVALID_SIZE = 13, /* Invalid size */
    CIOT_ERR_CLOSED = 14, /* Closed */
    CIOT_ERR_NOT_FOUND = 15, /* Resource not found */
    CIOT_ERR_VALIDATION_FAILED = 16, /* Validation failed */
    CIOT_ERR_CONNECTION = 17, /* Connection failed */
    CIOT_ERR_DISCONNECTION = 18, /* Disconnection failed */
    CIOT_ERR_EXCEPTION = 19, /* Unknown exception occours */
    CIOT_ERR_INVALID_ARG = 20, /* Invalid argument detected */
    CIOT_ERR_NO_MEMORY = 21, /* Insuficient memory */
    CIOT_ERR_TIMEOUT = 22, /* Timeout */
    CIOT_ERR_MONGOOSE = 23, /* Internal error on mongoose framework */
    CIOT_ERR_IMPOSSIBLE_OP = 24, /* Requested operation is impossible */
    CIOT_ERR_CHECKSUM = 25, /* Checksum validation error */
    CIOT_ERR_PROTOCOL_VIOLATION = 26, /* Protocol validation error */
    CIOT_ERR_DATA_LOSS = 27, /* Data loss */
    CIOT_ERR_INVALID_HEADER = 28, /* Invalid message header */
    CIOT_ERR_DISABLED = 29, /* Feature disabled */
    CIOT_ERR_FAIL = 30, /* Operation failed */
    CIOT_ERR_INVALID_INDEX = 31, /* Invalid index */
    CIOT_ERR_INVALID_KEY_SIZE = 32, /* Invalid key size */
    CIOT_ERR_FIFO_READ = 33, /* Error reading fifo data */
    CIOT_ERR_FIFO_WRITE = 34, /* Error writing data to fifo */
    CIOT_ERR_INVALID_ADDR = 35, /* Invalid address */
    CIOT_ERR_RESOURCES = 36, /* Not enough resources */
    CIOT_ERR_UNKNOWN = 37, /* Unknown error */
    CIOT_ERR_READING = 38, /* Reading error */
    CIOT_ERR_ERASING = 39, /* Erasing error */
    CIOT_ERR_WRITING = 40, /* Writing error */
    CIOT_ERR_INVALID_NAME = 41, /* Invalid name error */
    CIOT_ERR_DECODER_MISSING = 42, /* Decoder is missing */
    CIOT_ERR_SERIALIZER_MISSING = 43, /* Serializer is missing */
    CIOT_ERR_SMALL_RAW = 44 /* Data size is greater than raw bytes array */
} ciot_err_t;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _CIOT_ERR_MIN CIOT_ERR_OK
#define _CIOT_ERR_MAX CIOT_ERR_SMALL_RAW
#define _CIOT_ERR_ARRAYSIZE ((ciot_err_t)(CIOT_ERR_SMALL_RAW+1))
#define CIOT_ERR_ERR_OK CIOT_ERR_OK
#define CIOT_ERR_ERR_NULL_ARG CIOT_ERR_NULL_ARG
#define CIOT_ERR_ERR_INVALID_ID CIOT_ERR_INVALID_ID
#define CIOT_ERR_ERR_INVALID_TYPE CIOT_ERR_INVALID_TYPE
#define CIOT_ERR_ERR_OVERFLOW CIOT_ERR_OVERFLOW
#define CIOT_ERR_ERR_NOT_IMPLEMENTED CIOT_ERR_NOT_IMPLEMENTED
#define CIOT_ERR_ERR_NOT_SUPPORTED CIOT_ERR_NOT_SUPPORTED
#define CIOT_ERR_ERR_BUSY CIOT_ERR_BUSY
#define CIOT_ERR_ERR_INVALID_STATE CIOT_ERR_INVALID_STATE
#define CIOT_ERR_ERR_SERIALIZATION CIOT_ERR_SERIALIZATION
#define CIOT_ERR_ERR_DESERIALIZATION CIOT_ERR_DESERIALIZATION
#define CIOT_ERR_ERR_SEND_DATA CIOT_ERR_SEND_DATA
#define CIOT_ERR_ERR_RECV_DATA CIOT_ERR_RECV_DATA
#define CIOT_ERR_ERR_INVALID_SIZE CIOT_ERR_INVALID_SIZE
#define CIOT_ERR_ERR_CLOSED CIOT_ERR_CLOSED
#define CIOT_ERR_ERR_NOT_FOUND CIOT_ERR_NOT_FOUND
#define CIOT_ERR_ERR_VALIDATION_FAILED CIOT_ERR_VALIDATION_FAILED
#define CIOT_ERR_ERR_CONNECTION CIOT_ERR_CONNECTION
#define CIOT_ERR_ERR_DISCONNECTION CIOT_ERR_DISCONNECTION
#define CIOT_ERR_ERR_EXCEPTION CIOT_ERR_EXCEPTION
#define CIOT_ERR_ERR_INVALID_ARG CIOT_ERR_INVALID_ARG
#define CIOT_ERR_ERR_NO_MEMORY CIOT_ERR_NO_MEMORY
#define CIOT_ERR_ERR_TIMEOUT CIOT_ERR_TIMEOUT
#define CIOT_ERR_ERR_MONGOOSE CIOT_ERR_MONGOOSE
#define CIOT_ERR_ERR_IMPOSSIBLE_OP CIOT_ERR_IMPOSSIBLE_OP
#define CIOT_ERR_ERR_CHECKSUM CIOT_ERR_CHECKSUM
#define CIOT_ERR_ERR_PROTOCOL_VIOLATION CIOT_ERR_PROTOCOL_VIOLATION
#define CIOT_ERR_ERR_DATA_LOSS CIOT_ERR_DATA_LOSS
#define CIOT_ERR_ERR_INVALID_HEADER CIOT_ERR_INVALID_HEADER
#define CIOT_ERR_ERR_DISABLED CIOT_ERR_DISABLED
#define CIOT_ERR_ERR_FAIL CIOT_ERR_FAIL
#define CIOT_ERR_ERR_INVALID_INDEX CIOT_ERR_INVALID_INDEX
#define CIOT_ERR_ERR_INVALID_KEY_SIZE CIOT_ERR_INVALID_KEY_SIZE
#define CIOT_ERR_ERR_FIFO_READ CIOT_ERR_FIFO_READ
#define CIOT_ERR_ERR_FIFO_WRITE CIOT_ERR_FIFO_WRITE
#define CIOT_ERR_ERR_INVALID_ADDR CIOT_ERR_INVALID_ADDR
#define CIOT_ERR_ERR_RESOURCES CIOT_ERR_RESOURCES
#define CIOT_ERR_ERR_UNKNOWN CIOT_ERR_UNKNOWN
#define CIOT_ERR_ERR_READING CIOT_ERR_READING
#define CIOT_ERR_ERR_ERASING CIOT_ERR_ERASING
#define CIOT_ERR_ERR_WRITING CIOT_ERR_WRITING
#define CIOT_ERR_ERR_INVALID_NAME CIOT_ERR_INVALID_NAME
#define CIOT_ERR_ERR_DECODER_MISSING CIOT_ERR_DECODER_MISSING
#define CIOT_ERR_ERR_SERIALIZER_MISSING CIOT_ERR_SERIALIZER_MISSING
#define CIOT_ERR_ERR_SMALL_RAW CIOT_ERR_SMALL_RAW


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
