/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ciot/proto/v2/gpio.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CIOT_GPIO_STOP, ciot_gpio_stop_t, AUTO)


PB_BIND(CIOT_GPIO_PIN_CFG, ciot_gpio_pin_cfg_t, AUTO)


PB_BIND(CIOT_GPIO_CFG, ciot_gpio_cfg_t, AUTO)


PB_BIND(CIOT_GPIO_STATUS, ciot_gpio_status_t, AUTO)


PB_BIND(CIOT_GPIO_STATE_INFO, ciot_gpio_state_info_t, AUTO)


PB_BIND(CIOT_GPIO_REQ, ciot_gpio_req_t, AUTO)


PB_BIND(CIOT_GPIO_DATA, ciot_gpio_data_t, AUTO)









