/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_CIOT_CIOT_PROTO_V2_IFACE_MANAGER_PB_H_INCLUDED
#define PB_CIOT_CIOT_PROTO_V2_IFACE_MANAGER_PB_H_INCLUDED
#include <pb.h>
#include "ciot/proto/v2/msg.pb.h"
#include "ciot/proto/v2/iface.pb.h"
#include "ciot/proto/v2/event.pb.h"
#include "google/protobuf/empty.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct ciot_ifaces_list {
    pb_callback_t items;
} ciot_ifaces_list_t;

typedef struct ciot_create_iface_request {
    bool has_message;
    ciot_msg_t message;
} ciot_create_iface_request_t;

typedef struct ciot_create_iface_response {
    bool has_message;
    ciot_msg_t message;
} ciot_create_iface_response_t;

typedef struct ciot_get_iface_request {
    uint32_t id;
} ciot_get_iface_request_t;

typedef struct ciot_get_iface_response {
    bool has_message;
    ciot_msg_t message;
} ciot_get_iface_response_t;

typedef struct ciot_get_ifaces_response {
    pb_callback_t list;
} ciot_get_ifaces_response_t;

typedef struct ciot_update_iface_request {
    bool has_message;
    ciot_msg_t message;
} ciot_update_iface_request_t;

typedef struct ciot_update_iface_response {
    bool has_message;
    ciot_msg_t message;
} ciot_update_iface_response_t;

typedef struct ciot_delete_iface_request {
    uint32_t id;
} ciot_delete_iface_request_t;

typedef struct ciot_delete_iface_response {
    bool has_message;
    ciot_msg_t message;
} ciot_delete_iface_response_t;

typedef struct ciot_select_iface_request {
    uint32_t id;
} ciot_select_iface_request_t;

typedef struct ciot_select_iface_response {
    bool has_iface;
    ciot_iface_info_t iface;
} ciot_select_iface_response_t;

typedef struct ciot_get_selected_iface_response {
    bool has_iface;
    ciot_iface_info_t iface;
} ciot_get_selected_iface_response_t;

typedef struct ciot_send_message_request {
    bool has_message;
    ciot_msg_t message;
} ciot_send_message_request_t;

typedef struct ciot_send_message_response {
    bool has_message;
    ciot_msg_t message;
} ciot_send_message_response_t;

typedef struct ciot_subscribe_to_events_request {
    pb_callback_t id;
    bool has_iface;
    ciot_iface_info_t iface;
} ciot_subscribe_to_events_request_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CIOT_IFACES_LIST_INIT_DEFAULT            {{{NULL}, NULL}}
#define CIOT_CREATE_IFACE_REQUEST_INIT_DEFAULT   {false, CIOT_MSG_INIT_DEFAULT}
#define CIOT_CREATE_IFACE_RESPONSE_INIT_DEFAULT  {false, CIOT_MSG_INIT_DEFAULT}
#define CIOT_GET_IFACE_REQUEST_INIT_DEFAULT      {0}
#define CIOT_GET_IFACE_RESPONSE_INIT_DEFAULT     {false, CIOT_MSG_INIT_DEFAULT}
#define CIOT_GET_IFACES_RESPONSE_INIT_DEFAULT    {{{NULL}, NULL}}
#define CIOT_UPDATE_IFACE_REQUEST_INIT_DEFAULT   {false, CIOT_MSG_INIT_DEFAULT}
#define CIOT_UPDATE_IFACE_RESPONSE_INIT_DEFAULT  {false, CIOT_MSG_INIT_DEFAULT}
#define CIOT_DELETE_IFACE_REQUEST_INIT_DEFAULT   {0}
#define CIOT_DELETE_IFACE_RESPONSE_INIT_DEFAULT  {false, CIOT_MSG_INIT_DEFAULT}
#define CIOT_SELECT_IFACE_REQUEST_INIT_DEFAULT   {0}
#define CIOT_SELECT_IFACE_RESPONSE_INIT_DEFAULT  {false, CIOT_IFACE_INFO_INIT_DEFAULT}
#define CIOT_GET_SELECTED_IFACE_RESPONSE_INIT_DEFAULT {false, CIOT_IFACE_INFO_INIT_DEFAULT}
#define CIOT_SEND_MESSAGE_REQUEST_INIT_DEFAULT   {false, CIOT_MSG_INIT_DEFAULT}
#define CIOT_SEND_MESSAGE_RESPONSE_INIT_DEFAULT  {false, CIOT_MSG_INIT_DEFAULT}
#define CIOT_SUBSCRIBE_TO_EVENTS_REQUEST_INIT_DEFAULT {{{NULL}, NULL}, false, CIOT_IFACE_INFO_INIT_DEFAULT}
#define CIOT_IFACES_LIST_INIT_ZERO               {{{NULL}, NULL}}
#define CIOT_CREATE_IFACE_REQUEST_INIT_ZERO      {false, CIOT_MSG_INIT_ZERO}
#define CIOT_CREATE_IFACE_RESPONSE_INIT_ZERO     {false, CIOT_MSG_INIT_ZERO}
#define CIOT_GET_IFACE_REQUEST_INIT_ZERO         {0}
#define CIOT_GET_IFACE_RESPONSE_INIT_ZERO        {false, CIOT_MSG_INIT_ZERO}
#define CIOT_GET_IFACES_RESPONSE_INIT_ZERO       {{{NULL}, NULL}}
#define CIOT_UPDATE_IFACE_REQUEST_INIT_ZERO      {false, CIOT_MSG_INIT_ZERO}
#define CIOT_UPDATE_IFACE_RESPONSE_INIT_ZERO     {false, CIOT_MSG_INIT_ZERO}
#define CIOT_DELETE_IFACE_REQUEST_INIT_ZERO      {0}
#define CIOT_DELETE_IFACE_RESPONSE_INIT_ZERO     {false, CIOT_MSG_INIT_ZERO}
#define CIOT_SELECT_IFACE_REQUEST_INIT_ZERO      {0}
#define CIOT_SELECT_IFACE_RESPONSE_INIT_ZERO     {false, CIOT_IFACE_INFO_INIT_ZERO}
#define CIOT_GET_SELECTED_IFACE_RESPONSE_INIT_ZERO {false, CIOT_IFACE_INFO_INIT_ZERO}
#define CIOT_SEND_MESSAGE_REQUEST_INIT_ZERO      {false, CIOT_MSG_INIT_ZERO}
#define CIOT_SEND_MESSAGE_RESPONSE_INIT_ZERO     {false, CIOT_MSG_INIT_ZERO}
#define CIOT_SUBSCRIBE_TO_EVENTS_REQUEST_INIT_ZERO {{{NULL}, NULL}, false, CIOT_IFACE_INFO_INIT_ZERO}

/* Field tags (for use in manual encoding/decoding) */
#define CIOT_IFACES_LIST_ITEMS_TAG               1
#define CIOT_CREATE_IFACE_REQUEST_MESSAGE_TAG    1
#define CIOT_CREATE_IFACE_RESPONSE_MESSAGE_TAG   1
#define CIOT_GET_IFACE_REQUEST_ID_TAG            1
#define CIOT_GET_IFACE_RESPONSE_MESSAGE_TAG      1
#define CIOT_GET_IFACES_RESPONSE_LIST_TAG        1
#define CIOT_UPDATE_IFACE_REQUEST_MESSAGE_TAG    1
#define CIOT_UPDATE_IFACE_RESPONSE_MESSAGE_TAG   1
#define CIOT_DELETE_IFACE_REQUEST_ID_TAG         1
#define CIOT_DELETE_IFACE_RESPONSE_MESSAGE_TAG   1
#define CIOT_SELECT_IFACE_REQUEST_ID_TAG         1
#define CIOT_SELECT_IFACE_RESPONSE_IFACE_TAG     1
#define CIOT_GET_SELECTED_IFACE_RESPONSE_IFACE_TAG 1
#define CIOT_SEND_MESSAGE_REQUEST_MESSAGE_TAG    1
#define CIOT_SEND_MESSAGE_RESPONSE_MESSAGE_TAG   1
#define CIOT_SUBSCRIBE_TO_EVENTS_REQUEST_ID_TAG  1
#define CIOT_SUBSCRIBE_TO_EVENTS_REQUEST_IFACE_TAG 2

/* Struct field encoding specification for nanopb */
#define CIOT_IFACES_LIST_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  items,             1)
#define CIOT_IFACES_LIST_CALLBACK pb_default_field_callback
#define CIOT_IFACES_LIST_DEFAULT NULL
#define ciot_ifaces_list_t_items_MSGTYPE ciot_msg_t

#define CIOT_CREATE_IFACE_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define CIOT_CREATE_IFACE_REQUEST_CALLBACK NULL
#define CIOT_CREATE_IFACE_REQUEST_DEFAULT NULL
#define ciot_create_iface_request_t_message_MSGTYPE ciot_msg_t

#define CIOT_CREATE_IFACE_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define CIOT_CREATE_IFACE_RESPONSE_CALLBACK NULL
#define CIOT_CREATE_IFACE_RESPONSE_DEFAULT NULL
#define ciot_create_iface_response_t_message_MSGTYPE ciot_msg_t

#define CIOT_GET_IFACE_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define CIOT_GET_IFACE_REQUEST_CALLBACK NULL
#define CIOT_GET_IFACE_REQUEST_DEFAULT NULL

#define CIOT_GET_IFACE_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define CIOT_GET_IFACE_RESPONSE_CALLBACK NULL
#define CIOT_GET_IFACE_RESPONSE_DEFAULT NULL
#define ciot_get_iface_response_t_message_MSGTYPE ciot_msg_t

#define CIOT_GET_IFACES_RESPONSE_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  list,              1)
#define CIOT_GET_IFACES_RESPONSE_CALLBACK pb_default_field_callback
#define CIOT_GET_IFACES_RESPONSE_DEFAULT NULL
#define ciot_get_ifaces_response_t_list_MSGTYPE ciot_msg_t

#define CIOT_UPDATE_IFACE_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define CIOT_UPDATE_IFACE_REQUEST_CALLBACK NULL
#define CIOT_UPDATE_IFACE_REQUEST_DEFAULT NULL
#define ciot_update_iface_request_t_message_MSGTYPE ciot_msg_t

#define CIOT_UPDATE_IFACE_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define CIOT_UPDATE_IFACE_RESPONSE_CALLBACK NULL
#define CIOT_UPDATE_IFACE_RESPONSE_DEFAULT NULL
#define ciot_update_iface_response_t_message_MSGTYPE ciot_msg_t

#define CIOT_DELETE_IFACE_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define CIOT_DELETE_IFACE_REQUEST_CALLBACK NULL
#define CIOT_DELETE_IFACE_REQUEST_DEFAULT NULL

#define CIOT_DELETE_IFACE_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define CIOT_DELETE_IFACE_RESPONSE_CALLBACK NULL
#define CIOT_DELETE_IFACE_RESPONSE_DEFAULT NULL
#define ciot_delete_iface_response_t_message_MSGTYPE ciot_msg_t

#define CIOT_SELECT_IFACE_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define CIOT_SELECT_IFACE_REQUEST_CALLBACK NULL
#define CIOT_SELECT_IFACE_REQUEST_DEFAULT NULL

#define CIOT_SELECT_IFACE_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  iface,             1)
#define CIOT_SELECT_IFACE_RESPONSE_CALLBACK NULL
#define CIOT_SELECT_IFACE_RESPONSE_DEFAULT NULL
#define ciot_select_iface_response_t_iface_MSGTYPE ciot_iface_info_t

#define CIOT_GET_SELECTED_IFACE_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  iface,             1)
#define CIOT_GET_SELECTED_IFACE_RESPONSE_CALLBACK NULL
#define CIOT_GET_SELECTED_IFACE_RESPONSE_DEFAULT NULL
#define ciot_get_selected_iface_response_t_iface_MSGTYPE ciot_iface_info_t

#define CIOT_SEND_MESSAGE_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define CIOT_SEND_MESSAGE_REQUEST_CALLBACK NULL
#define CIOT_SEND_MESSAGE_REQUEST_DEFAULT NULL
#define ciot_send_message_request_t_message_MSGTYPE ciot_msg_t

#define CIOT_SEND_MESSAGE_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define CIOT_SEND_MESSAGE_RESPONSE_CALLBACK NULL
#define CIOT_SEND_MESSAGE_RESPONSE_DEFAULT NULL
#define ciot_send_message_response_t_message_MSGTYPE ciot_msg_t

#define CIOT_SUBSCRIBE_TO_EVENTS_REQUEST_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  iface,             2)
#define CIOT_SUBSCRIBE_TO_EVENTS_REQUEST_CALLBACK pb_default_field_callback
#define CIOT_SUBSCRIBE_TO_EVENTS_REQUEST_DEFAULT NULL
#define ciot_subscribe_to_events_request_t_iface_MSGTYPE ciot_iface_info_t

extern const pb_msgdesc_t ciot_ifaces_list_t_msg;
extern const pb_msgdesc_t ciot_create_iface_request_t_msg;
extern const pb_msgdesc_t ciot_create_iface_response_t_msg;
extern const pb_msgdesc_t ciot_get_iface_request_t_msg;
extern const pb_msgdesc_t ciot_get_iface_response_t_msg;
extern const pb_msgdesc_t ciot_get_ifaces_response_t_msg;
extern const pb_msgdesc_t ciot_update_iface_request_t_msg;
extern const pb_msgdesc_t ciot_update_iface_response_t_msg;
extern const pb_msgdesc_t ciot_delete_iface_request_t_msg;
extern const pb_msgdesc_t ciot_delete_iface_response_t_msg;
extern const pb_msgdesc_t ciot_select_iface_request_t_msg;
extern const pb_msgdesc_t ciot_select_iface_response_t_msg;
extern const pb_msgdesc_t ciot_get_selected_iface_response_t_msg;
extern const pb_msgdesc_t ciot_send_message_request_t_msg;
extern const pb_msgdesc_t ciot_send_message_response_t_msg;
extern const pb_msgdesc_t ciot_subscribe_to_events_request_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CIOT_IFACES_LIST_FIELDS &ciot_ifaces_list_t_msg
#define CIOT_CREATE_IFACE_REQUEST_FIELDS &ciot_create_iface_request_t_msg
#define CIOT_CREATE_IFACE_RESPONSE_FIELDS &ciot_create_iface_response_t_msg
#define CIOT_GET_IFACE_REQUEST_FIELDS &ciot_get_iface_request_t_msg
#define CIOT_GET_IFACE_RESPONSE_FIELDS &ciot_get_iface_response_t_msg
#define CIOT_GET_IFACES_RESPONSE_FIELDS &ciot_get_ifaces_response_t_msg
#define CIOT_UPDATE_IFACE_REQUEST_FIELDS &ciot_update_iface_request_t_msg
#define CIOT_UPDATE_IFACE_RESPONSE_FIELDS &ciot_update_iface_response_t_msg
#define CIOT_DELETE_IFACE_REQUEST_FIELDS &ciot_delete_iface_request_t_msg
#define CIOT_DELETE_IFACE_RESPONSE_FIELDS &ciot_delete_iface_response_t_msg
#define CIOT_SELECT_IFACE_REQUEST_FIELDS &ciot_select_iface_request_t_msg
#define CIOT_SELECT_IFACE_RESPONSE_FIELDS &ciot_select_iface_response_t_msg
#define CIOT_GET_SELECTED_IFACE_RESPONSE_FIELDS &ciot_get_selected_iface_response_t_msg
#define CIOT_SEND_MESSAGE_REQUEST_FIELDS &ciot_send_message_request_t_msg
#define CIOT_SEND_MESSAGE_RESPONSE_FIELDS &ciot_send_message_response_t_msg
#define CIOT_SUBSCRIBE_TO_EVENTS_REQUEST_FIELDS &ciot_subscribe_to_events_request_t_msg

/* Maximum encoded size of messages (where known) */
/* Ciot_IfacesList_size depends on runtime parameters */
/* Ciot_GetIfacesResponse_size depends on runtime parameters */
/* Ciot_SubscribeToEventsRequest_size depends on runtime parameters */
#if defined(Ciot_Msg_size)
#define CIOT_CREATE_IFACE_REQUEST_SIZE           (6 + Ciot_Msg_size)
#define CIOT_CREATE_IFACE_RESPONSE_SIZE          (6 + Ciot_Msg_size)
#define CIOT_DELETE_IFACE_RESPONSE_SIZE          (6 + Ciot_Msg_size)
#define CIOT_GET_IFACE_RESPONSE_SIZE             (6 + Ciot_Msg_size)
#define CIOT_SEND_MESSAGE_REQUEST_SIZE           (6 + Ciot_Msg_size)
#define CIOT_SEND_MESSAGE_RESPONSE_SIZE          (6 + Ciot_Msg_size)
#define CIOT_UPDATE_IFACE_REQUEST_SIZE           (6 + Ciot_Msg_size)
#define CIOT_UPDATE_IFACE_RESPONSE_SIZE          (6 + Ciot_Msg_size)
#endif
#define CIOT_CIOT_PROTO_V2_IFACE_MANAGER_PB_H_MAX_SIZE CIOT_SELECT_IFACE_RESPONSE_SIZE
#define CIOT_DELETE_IFACE_REQUEST_SIZE           6
#define CIOT_GET_IFACE_REQUEST_SIZE              6
#define CIOT_GET_SELECTED_IFACE_RESPONSE_SIZE    10
#define CIOT_SELECT_IFACE_REQUEST_SIZE           6
#define CIOT_SELECT_IFACE_RESPONSE_SIZE          10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
