/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ciot/proto/v2/mbus_server.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CIOT_MBUS_SERVER_STOP, ciot_mbus_server_stop_t, AUTO)


PB_BIND(CIOT_MBUS_SERVER_RTU_CFG, ciot_mbus_server_rtu_cfg_t, AUTO)


PB_BIND(CIOT_MBUS_SERVER_TCP_CFG, ciot_mbus_server_tcp_cfg_t, AUTO)


PB_BIND(CIOT_MBUS_SERVER_CFG, ciot_mbus_server_cfg_t, AUTO)


PB_BIND(CIOT_MBUS_SERVER_STATUS, ciot_mbus_server_status_t, AUTO)


PB_BIND(CIOT_MBUS_SERVER_REQ, ciot_mbus_server_req_t, AUTO)


PB_BIND(CIOT_MBUS_SERVER_DATA, ciot_mbus_server_data_t, AUTO)





