/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ciot/proto/v2/msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ciot/proto/v2/msg.pb-c.h"
void   ciot__msg_error__init
                     (Ciot__MsgError         *message)
{
  static const Ciot__MsgError init_value = CIOT__MSG_ERROR__INIT;
  *message = init_value;
}
size_t ciot__msg_error__get_packed_size
                     (const Ciot__MsgError *message)
{
  assert(message->base.descriptor == &ciot__msg_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__msg_error__pack
                     (const Ciot__MsgError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__msg_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__msg_error__pack_to_buffer
                     (const Ciot__MsgError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__msg_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__MsgError *
       ciot__msg_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__MsgError *)
     protobuf_c_message_unpack (&ciot__msg_error__descriptor,
                                allocator, len, data);
}
void   ciot__msg_error__free_unpacked
                     (Ciot__MsgError *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__msg_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__msg_header__init
                     (Ciot__MsgHeader         *message)
{
  static const Ciot__MsgHeader init_value = CIOT__MSG_HEADER__INIT;
  *message = init_value;
}
size_t ciot__msg_header__get_packed_size
                     (const Ciot__MsgHeader *message)
{
  assert(message->base.descriptor == &ciot__msg_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__msg_header__pack
                     (const Ciot__MsgHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__msg_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__msg_header__pack_to_buffer
                     (const Ciot__MsgHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__msg_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__MsgHeader *
       ciot__msg_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__MsgHeader *)
     protobuf_c_message_unpack (&ciot__msg_header__descriptor,
                                allocator, len, data);
}
void   ciot__msg_header__free_unpacked
                     (Ciot__MsgHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__msg_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciot__msg__init
                     (Ciot__Msg         *message)
{
  static const Ciot__Msg init_value = CIOT__MSG__INIT;
  *message = init_value;
}
size_t ciot__msg__get_packed_size
                     (const Ciot__Msg *message)
{
  assert(message->base.descriptor == &ciot__msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciot__msg__pack
                     (const Ciot__Msg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciot__msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciot__msg__pack_to_buffer
                     (const Ciot__Msg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciot__msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ciot__Msg *
       ciot__msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ciot__Msg *)
     protobuf_c_message_unpack (&ciot__msg__descriptor,
                                allocator, len, data);
}
void   ciot__msg__free_unpacked
                     (Ciot__Msg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciot__msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ciot__msg_error__field_descriptors[3] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__MsgError, msg),
    &ciot__msg_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iface",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__MsgError, iface),
    &ciot__iface_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__MsgError, code),
    &ciot__err__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__msg_error__field_indices_by_name[] = {
  2,   /* field[2] = code */
  1,   /* field[1] = iface */
  0,   /* field[0] = msg */
};
static const ProtobufCIntRange ciot__msg_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ciot__msg_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.MsgError",
  "MsgError",
  "Ciot__MsgError",
  "Ciot",
  sizeof(Ciot__MsgError),
  3,
  ciot__msg_error__field_descriptors,
  ciot__msg_error__field_indices_by_name,
  1,  ciot__msg_error__number_ranges,
  (ProtobufCMessageInit) ciot__msg_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__msg_header__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__MsgHeader, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__MsgHeader, type),
    &ciot__msg_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iface",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__MsgHeader, iface),
    &ciot__iface_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__msg_header__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = iface */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange ciot__msg_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ciot__msg_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.MsgHeader",
  "MsgHeader",
  "Ciot__MsgHeader",
  "Ciot",
  sizeof(Ciot__MsgHeader),
  3,
  ciot__msg_header__field_descriptors,
  ciot__msg_header__field_indices_by_name,
  1,  ciot__msg_header__number_ranges,
  (ProtobufCMessageInit) ciot__msg_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciot__msg__field_descriptors[26] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ciot__Msg, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Ciot__Msg, type),
    &ciot__msg_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iface",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ciot__Msg, iface),
    &ciot__iface_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, error),
    &ciot__msg_error__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, payload),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, model),
    &ciot__model_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, log),
    &ciot__log__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ciot",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, ciot),
    &ciot__ciot_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "storage",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, storage),
    &ciot__storage_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sys",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, sys),
    &ciot__sys_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uart",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, uart),
    &ciot__uart_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usb",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, usb),
    &ciot__usb_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcp",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, tcp),
    &ciot__tcp_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eth",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, eth),
    &ciot__tcp_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wifi",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, wifi),
    &ciot__wifi_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ble",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, ble),
    &ciot__ble_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ble_scn",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, ble_scn),
    &ciot__ble_scn_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ble_adv",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, ble_adv),
    &ciot__ble_adv_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ntp",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, ntp),
    &ciot__ntp_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ota",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, ota),
    &ciot__ota_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dfu",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, dfu),
    &ciot__dfu_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "http_server",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, http_server),
    &ciot__http_server_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "http_client",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, http_client),
    &ciot__http_client_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mqtt_client",
    24,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, mqtt_client),
    &ciot__mqtt_client_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "socket",
    25,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, socket),
    &ciot__socket_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpio",
    26,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ciot__Msg, data_case),
    offsetof(Ciot__Msg, gpio),
    &ciot__gpio_data__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciot__msg__field_indices_by_name[] = {
  15,   /* field[15] = ble */
  17,   /* field[17] = ble_adv */
  16,   /* field[16] = ble_scn */
  7,   /* field[7] = ciot */
  20,   /* field[20] = dfu */
  3,   /* field[3] = error */
  13,   /* field[13] = eth */
  25,   /* field[25] = gpio */
  22,   /* field[22] = http_client */
  21,   /* field[21] = http_server */
  0,   /* field[0] = id */
  2,   /* field[2] = iface */
  6,   /* field[6] = log */
  5,   /* field[5] = model */
  23,   /* field[23] = mqtt_client */
  18,   /* field[18] = ntp */
  19,   /* field[19] = ota */
  4,   /* field[4] = payload */
  24,   /* field[24] = socket */
  8,   /* field[8] = storage */
  9,   /* field[9] = sys */
  12,   /* field[12] = tcp */
  1,   /* field[1] = type */
  10,   /* field[10] = uart */
  11,   /* field[11] = usb */
  14,   /* field[14] = wifi */
};
static const ProtobufCIntRange ciot__msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 26 }
};
const ProtobufCMessageDescriptor ciot__msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ciot.Msg",
  "Msg",
  "Ciot__Msg",
  "Ciot",
  sizeof(Ciot__Msg),
  26,
  ciot__msg__field_descriptors,
  ciot__msg__field_indices_by_name,
  1,  ciot__msg__number_ranges,
  (ProtobufCMessageInit) ciot__msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ciot__msg_type__enum_values_by_number[12] =
{
  { "MSG_TYPE_UNKNOWN", "CIOT__MSG_TYPE__MSG_TYPE_UNKNOWN", 0 },
  { "MSG_TYPE_CUSTOM", "CIOT__MSG_TYPE__MSG_TYPE_CUSTOM", 1 },
  { "MSG_TYPE_START", "CIOT__MSG_TYPE__MSG_TYPE_START", 2 },
  { "MSG_TYPE_STOP", "CIOT__MSG_TYPE__MSG_TYPE_STOP", 3 },
  { "MSG_TYPE_CONFIG", "CIOT__MSG_TYPE__MSG_TYPE_CONFIG", 4 },
  { "MSG_TYPE_INFO", "CIOT__MSG_TYPE__MSG_TYPE_INFO", 5 },
  { "MSG_TYPE_STATUS", "CIOT__MSG_TYPE__MSG_TYPE_STATUS", 6 },
  { "MSG_TYPE_SEND_PAYLOAD", "CIOT__MSG_TYPE__MSG_TYPE_SEND_PAYLOAD", 7 },
  { "MSG_TYPE_REQUEST", "CIOT__MSG_TYPE__MSG_TYPE_REQUEST", 8 },
  { "MSG_TYPE_ERROR", "CIOT__MSG_TYPE__MSG_TYPE_ERROR", 9 },
  { "MSG_TYPE_EVENT", "CIOT__MSG_TYPE__MSG_TYPE_EVENT", 10 },
  { "MSG_TYPE_LOG", "CIOT__MSG_TYPE__MSG_TYPE_LOG", 11 },
};
static const ProtobufCIntRange ciot__msg_type__value_ranges[] = {
{0, 0},{0, 12}
};
static const ProtobufCEnumValueIndex ciot__msg_type__enum_values_by_name[12] =
{
  { "MSG_TYPE_CONFIG", 4 },
  { "MSG_TYPE_CUSTOM", 1 },
  { "MSG_TYPE_ERROR", 9 },
  { "MSG_TYPE_EVENT", 10 },
  { "MSG_TYPE_INFO", 5 },
  { "MSG_TYPE_LOG", 11 },
  { "MSG_TYPE_REQUEST", 8 },
  { "MSG_TYPE_SEND_PAYLOAD", 7 },
  { "MSG_TYPE_START", 2 },
  { "MSG_TYPE_STATUS", 6 },
  { "MSG_TYPE_STOP", 3 },
  { "MSG_TYPE_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor ciot__msg_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Ciot.MsgType",
  "MsgType",
  "Ciot__MsgType",
  "Ciot",
  12,
  ciot__msg_type__enum_values_by_number,
  12,
  ciot__msg_type__enum_values_by_name,
  1,
  ciot__msg_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
