/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ciot/proto/v2/msg_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CIOT_MSG_DATA, ciot_msg_data_t, 2)



