/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ciot/proto/v2/sys.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CIOT_SYS_STOP, ciot_sys_stop_t, AUTO)


PB_BIND(CIOT_SYS_CFG, ciot_sys_cfg_t, AUTO)


PB_BIND(CIOT_SYS_FEATURES, ciot_sys_features_t, AUTO)


PB_BIND(CIOT_SYS_INFO, ciot_sys_info_t, AUTO)


PB_BIND(CIOT_SYS_STATUS, ciot_sys_status_t, AUTO)


PB_BIND(CIOT_SYS_REQ, ciot_sys_req_t, AUTO)


PB_BIND(CIOT_SYS_DATA, ciot_sys_data_t, AUTO)







